--------------------------------------------------------
--  File created - Monday-January-05-2015   
--------------------------------------------------------

--------------------------------------------------------
--  DDL for Sequence SEQ_PG_ACTIVITY_LOG
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_PG_ACTIVITY_LOG"  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PG_BLACKLISTED_CARD
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_PG_BLACKLISTED_CARD"  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PG_EMV_TRANSACTION
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_PG_EMV_TRANSACTION"  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PG_FEATURES
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_PG_FEATURES"  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PG_FEE_DETAIL
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_PG_FEE_DETAIL"  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence SEQ_PG_MERCHANT
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_PG_MERCHANT"  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PG_MERCHANT_BANK
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_PG_MERCHANT_BANK"  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PG_ROLE_FEATURE_MAPPING
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_PG_ROLE_FEATURE_MAPPING"  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PG_SUB_FEATURES
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_PG_SUB_FEATURES"  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PG_SWITCH
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_PG_SWITCH"  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PG_SWITCH_TRANSACTION
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_PG_SWITCH_TRANSACTION"  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PG_TERMINAL
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_PG_TERMINAL"  MINVALUE 10 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PG_TERMINAL_SETTINGS
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_PG_TERMINAL_SETTINGS"  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PG_TRANSACTION
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_PG_TRANSACTION"  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PG_USER_ROLES
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_PG_USER_ROLES"  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
   
-----------------------------------------------------
--  DDL for Sequence SEQ_APPLICATION_CLIENT
--------------------------------------------------------
CREATE SEQUENCE  SEQ_APPLICATION_CLIENT  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;

-----------------------------------------------------
--  DDL for Sequence SEQ_PG_FRAUD_BASIC
--------------------------------------------------------
CREATE SEQUENCE  "SEQ_PG_FRAUD_BASIC"  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;

-----------------------------------------------------
--  DDL for Sequence SEQ_PG_ADMIN_USER
--------------------------------------------------------
CREATE SEQUENCE  "SEQ_PG_ADMIN_USER"  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Table PG_ACTIVITY_LOG
--------------------------------------------------------

  CREATE TABLE "PG_ACTIVITY_LOG" 
   (	"ID" NUMBER(10,0), 
	"SYS_TRACE_NUM" NUMBER(12,0), 
	"REQUEST_IP" VARCHAR2(20), 
	"REQUEST_PORT" NUMBER(5,0), 
	"RESPONSE_PORT" NUMBER(5,0), 
	"POS_ENTRY_MODE" VARCHAR2(20), 
	"CHIP_TRANSACTION" NUMBER(1,0) DEFAULT 0, 
	"PROCESSING_CODE" VARCHAR2(20), 
	"RESPONSE_CODE" VARCHAR2(20), 
	"F39" VARCHAR2(10), 
	"TXN_AMOUNT" NUMBER(10,2), 
	"ADJ_AMOUNT" NUMBER(10,2), 
	"MTI" VARCHAR2(4), 
	"PAN" VARCHAR2(150), 
	"PAN_MASKED" VARCHAR2(20), 
	"EXP_DATE" VARCHAR2(50), 
	"POS_TXN_DATE" VARCHAR2(4), 
	"POS_TXN_TIME" VARCHAR2(6), 
	"MCC" VARCHAR2(4), 
	"TXN_COUNTRY_CODE" VARCHAR2(3), 
	"TXN_CURRENCY_CODE" VARCHAR2(3), 
	"AI_COUNTRY_CODE" VARCHAR2(3), 
	"PAN_COUNTRY_CODE" VARCHAR2(3), 
	"FWD_COUNTRY_CODE" VARCHAR2(3), 
	"F55" VARCHAR2(1000),
	"REQ_DE07_TRANSMISSION_DATE" VARCHAR2(20),
	"DE37_RRN"                   VARCHAR2(50),
	"DE38_AUTH_ID"                   VARCHAR2(50),
	"DE41_MID"                   VARCHAR2(50),
 	"DE42_TID"                   VARCHAR2(50),
 	"DE43_ACCEPTOR_LOCATION"     VARCHAR2(50),
 	"RES_DE04_TXN_AMOUNT"        VARCHAR2(20),
  	"RES_DE07_TRANSMISSION_DATE" VARCHAR2(20),
  	"CREATED_DATE"               TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 	"UPDATED_DATE"               TIMESTAMP DEFAULT CURRENT_TIMESTAMP
   ) ;
--------------------------------------------------------
--  DDL for Table PG_BLACKLISTED_CARD
--------------------------------------------------------

  CREATE TABLE "PG_BLACKLISTED_CARD" 
   (	"ID" NUMBER(10,0), 
	"CARD_NUM" VARCHAR2(50), 
	"CREATED_DATE" TIMESTAMP (6), 
	"STATUS" NUMBER(1,0) DEFAULT 0
   ) ;
--------------------------------------------------------
--  DDL for Table PG_EMV_TRANSACTION
--------------------------------------------------------

  CREATE TABLE "PG_EMV_TRANSACTION" 
   (	"ID" NUMBER(10,0), 
	"PG_TRANSACTION_ID" NUMBER(12,0), 
	"AID" VARCHAR2(50), 
	"IST" VARCHAR2(50), 
	"IST1" VARCHAR2(50), 
	"AIP" VARCHAR2(50), 
	"IID" VARCHAR2(50), 
	"TVR" VARCHAR2(50), 
	"AED" VARCHAR2(50), 
	"FCI" VARCHAR2(50), 
	"FCIP" VARCHAR2(50), 
	"TXN_STATUS_INFO" VARCHAR2(50), 
	"PSL" VARCHAR2(50), 
	"TAVN" VARCHAR2(50), 
	"IAD" VARCHAR2(50), 
	"IFD" VARCHAR2(50), 
	"APP_CRYPTO" VARCHAR2(50), 
	"CRYPTO_INFO" VARCHAR2(50), 
	"TERMINAL_CAPABILITIES" VARCHAR2(50), 
	"CVMR" VARCHAR2(50), 
	"TERMINAL_TYPE" VARCHAR2(50), 
	"ATC" VARCHAR2(50), 
	"UNPRED_NUMBER" VARCHAR2(50), 
	"TSN" VARCHAR2(50), 
	"TCC" VARCHAR2(50), 
	"ISR" VARCHAR2(50), 
	"LAN_PREF" VARCHAR2(10)
   ) ;
--------------------------------------------------------
--  DDL for Table PG_FEATURES
--------------------------------------------------------

  CREATE TABLE "PG_FEATURES" 
   (	"FEATURE_ID" NUMBER(2,0), 
	"FEATURE_NAME" VARCHAR2(30), 
	"FEATURE_URL" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table PG_FEE_DETAIL
--------------------------------------------------------

  CREATE TABLE "PG_FEE_DETAIL" 
   (	"ID" NUMBER(10,0), 
	"TXN_TYPE" VARCHAR2(20), 
	"FEE_AMOUNT" NUMBER(10,2), 
	"CREATED_DATE" TIMESTAMP (6), 
	"STATUS" NUMBER(1,0) DEFAULT 0
   ) ;

--------------------------------------------------------
--  DDL for Table PG_MERCHANT_BANK
--------------------------------------------------------

 CREATE TABLE "PG_MERCHANT_BANK"
  (
    "ID"             NUMBER(10,0),
    "MERCHANT_ID"    NUMBER(15,0),
    "BANK_NAME"      VARCHAR2(50),
    "BANK_ACC_NUM"   VARCHAR2(20),
    "BANK_CODE"      VARCHAR2(20),
    "ROUTING_NUMBER" VARCHAR2(20),
    "CURRENCY_CODE"  NUMBER(3,0),
    "ACCOUNT_TYPE"   VARCHAR2(20),
    "STATUS"         NUMBER(1,0) DEFAULT 0,
    "CREATED_DATE"   TIMESTAMP (6),
    "UPDATED_DATE"   TIMESTAMP (6),
    "CREATED_BY"     NUMBER(10,0),
    "ADDRESS1"       VARCHAR2(60 BYTE),
    "ADDRESS2"       VARCHAR2(60 BYTE),
    "CITY"           VARCHAR2(60 BYTE),
    "STATE"          VARCHAR2(60 BYTE),
    "COUNTRY"        VARCHAR2(60 BYTE),
    "PIN"            NUMBER(10,0)
  ) ;

--------------------------------------------------------
--  DDL for Table PG_ROLE_FEATURE_MAPPING
--------------------------------------------------------

  CREATE TABLE "PG_ROLE_FEATURE_MAPPING" 
   (	"ID" NUMBER(5,0), 
	"ROLE_ID" NUMBER(2,0), 
	"FEATURE_ID" NUMBER(2,0), 
	"DISPLAY_ORDER" NUMBER(3,0)
   ) ;
--------------------------------------------------------
--  DDL for Table PG_SUB_FEATURES
--------------------------------------------------------

  CREATE TABLE "PG_SUB_FEATURES" 
   (	"SUB_FEATURE_ID" NUMBER(2,0), 
	"FEATURE_ID" NUMBER(2,0), 
	"FEATURE_NAME" VARCHAR2(30), 
	"FEATURE_URL" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table PG_SWITCH
--------------------------------------------------------

  CREATE TABLE "PG_SWITCH" 
   (	"ID" NUMBER(10,0), 
	"SWITCH_NAME" VARCHAR2(50), 
	"SWITCH_TYPE" VARCHAR2(50), 
	"SWITCH_IP" VARCHAR2(50), 
	"SWITCH_PORT" VARCHAR2(50), 
	"STATUS" NUMBER(1,0), 
	"PRIORITY" NUMBER(2,0), 
	"CREATED_BY" NUMBER(10,0), 
	"UPDATED_BY" NUMBER(10,0)
   ) ;
--------------------------------------------------------
--  DDL for Table PG_SWITCH_TRANSACTION
--------------------------------------------------------

  CREATE TABLE "PG_SWITCH_TRANSACTION" 
   (	"ID" NUMBER(10,0), 
	"TRANSACTION_ID" NUMBER(12,0), 
	"PG_TRANSACTION_ID" NUMBER(12,0), 
	"SWITCH_ID" NUMBER(12,0) DEFAULT 1, 
	"PAN" VARCHAR2(150), 
	"PAN_MASKED" VARCHAR2(20), 
	"MCC" VARCHAR2(4), 
	"POS_ENTRY_MODE" VARCHAR2(4), 
	"TXN_AMOUNT" NUMBER(10,2), 
	"CREATED_DATE" TIMESTAMP (6), 
	"STATUS" NUMBER(1,0), 
	"SETTLEMENT_BATCH_ID" NUMBER(10,0), 
	"SETTLEMENT_BATCH_STATUS" NUMBER(1,0), 
	"TRANSACTION_CODE" VARCHAR2(50),
	"PROCESSOR_RESPONSE" VARCHAR2(500),
	"PROCESSOR_RESPONSE_MSG" VARCHAR2(500),
	"PROCESSOR_RESPONSE_TIME" TIMESTAMP(6),
	"PROCESSOR_RESPONSE_POST_DATE" TIMESTAMP(6),
	"PROCESSOR_MESSAGE" VARCHAR2(500),
	"PROCESSOR_AUTH_CODE" VARCHAR2(100),
	"PROCESSOR_APPROVED_AMT" NUMBER(10,0),
	"PROCESSOR_TXN_DUPLICATE" VARCHAR2(10)
   ) ;

--------------------------------------------------------
--  DDL for Table PG_TRANSACTION
--------------------------------------------------------

  CREATE TABLE "PG_TRANSACTION" 
   (	"ID" NUMBER(10,0), 
	"TRANSACTION_ID" NUMBER(12,0), 
	"REF_TRANSACTION_ID" NUMBER(12,0), 
	"AUTH_ID" NUMBER(12,0), 
	"INVOICE_NUMBER" NUMBER(12,0), 
	"SYS_TRACE_NUM" NUMBER(12,0), 
	"TXN_TYPE" VARCHAR2(20), 
	"PAYMENT_METHOD" VARCHAR2(20), 
	"TXN_AMOUNT" NUMBER(20,0), 
	"ADJ_AMOUNT" NUMBER(20,0), 
	"FEE_AMOUNT" NUMBER(20,0), 
	"TOTAL_AMOUNT" NUMBER(20,0), 
	"MERCHANT_ID" NUMBER(15,0), 
	"TERMINAL_ID" NUMBER(8,0), 
	"ACQ_CHANNEL" VARCHAR2(5) DEFAULT 'web', 
	"ACQ_TXN_MODE" VARCHAR2(20) DEFAULT 'rest', 
	"ISSUER_TXN_REF_NUM" NUMBER(20,0), 
	"CREATED_DATE" TIMESTAMP (6), 
	"UPDATED_DATE" TIMESTAMP (6), 
	"STATUS" NUMBER(1,0), 
	"CHIP_TRANSACTION" NUMBER(1,0) DEFAULT 0, 
	"CHIP_FALLBACK_TRANSACTION" NUMBER(1,0) DEFAULT 0, 
	"SETTLEMENT_BATCH_ID" NUMBER(10,0), 
	"SETTLEMENT_BATCH_STATUS" NUMBER(1,0), 
	"MTI" VARCHAR2(4), 
	"PROC_CODE" VARCHAR2(6), 
	"PAN" VARCHAR2(150), 
	"PAN_MASKED" VARCHAR2(20), 
	"EXP_DATE" VARCHAR2(50), 
	"POS_TXN_TIME" VARCHAR2(6), 
	"POS_TXN_DATE" VARCHAR2(4), 
	"MCC" VARCHAR2(4), 
	"POS_ENTRY_MODE" VARCHAR2(3), 
	"TXN_COUNTRY_CODE" VARCHAR2(3), 
	"TXN_CURRENCY_CODE" VARCHAR2(3), 
	"AI_COUNTRY_CODE" VARCHAR2(3), 
	"PAN_COUNTRY_CODE" VARCHAR2(3), 
	"FWD_COUNTRY_CODE" VARCHAR2(3),
	"PROCESSOR" VARCHAR2(50),
	"ACCOUNT_NUMBER" VARCHAR2(20)
   ) ;
--------------------------------------------------------
--  DDL for Table PG_USER_ROLES
--------------------------------------------------------

  CREATE TABLE "PG_USER_ROLES" 
   (	"ROLE_ID" NUMBER(2,0), 
	"ROLE_NAME" VARCHAR2(30)
   ) ;


--------------------------------------------------------
--  DDL for Sequence SEQ_PG_ONLINE_ACTIVITY_LOG
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_PG_ONLINE_TXN_LOG"  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Table PG_ONLINE_TXN_LOG
--------------------------------------------------------
  CREATE TABLE "PG_ONLINE_TXN_LOG" 
   ( "ID" NUMBER(20,0), 
	 "ORDER_ID" VARCHAR2(50), 
	 "PROCESSOR_TXN_ID" VARCHAR2(50), 
	 "PG_TXN_ID" NUMBER(20,0), 
	 "TRANSACTION_TYPE" VARCHAR2(20), 
	 "REQUEST_IP_PORT"  VARCHAR2(60), 
	 "MERCHANT_ID" VARCHAR2(50), 
	 "TXN_TOTAL_AMOUNT" NUMBER(10,0), 
	 "MERCHANT_AMOUNT" NUMBER(10,0), 
	 "CARD_ASSOCIATION" VARCHAR2(10), 
	 "TXN_DESCRIPTION" VARCHAR2(150), 
	 "BILLER_NAME" VARCHAR2(150),
	 "BILLER_EMAIL" VARCHAR2(100), 
	 "BILLER_ADDRESS" VARCHAR2(100),
	 "BILLER_ADDRESS2" VARCHAR2(100),
	 "BILLER_CITY" VARCHAR2(100),
	 "BILLER_STATE" VARCHAR2(100),
	 "BILLER_COUNTRY" VARCHAR2(20),
	 "BILLER_ZIP" VARCHAR2(15),
	 "MERCHANT_RETURN_URL" VARCHAR2(500),
	 "PAN_DATA" VARCHAR2(150), 
	 "PAN_MASKED" VARCHAR2(20), 
	 "POS_TXN_DATE_TIME" NUMBER(20, 0), 
	 "PROCESSOR_RESPONSE" VARCHAR2(500),
	 "TXN_STATE" VARCHAR2(20),
	 "TXN_REASON"  VARCHAR2(250),
	 "REQUEST_DATE_TIME" TIMESTAMP (6),
	 "RESPONSE_DATE_TIME" TIMESTAMP (6)
   ) ;
   
--------------------------------------------------------
--  DDL for Table PG_APPLICATION_CLIENT
--------------------------------------------------------

CREATE TABLE PG_APPLICATION_CLIENT 
(	
	ID 	NUMBER(10,0) NOT NULL ENABLE,
	APP_NAME 				VARCHAR2(100) NOT NULL, 
	APP_DESCRIPTION 				VARCHAR2(300) NOT NULL, 
	APP_ADMIN_EMAIL 				VARCHAR2(150) NOT NULL, 
	APP_CLIENT_NAME 				VARCHAR2(150) NOT NULL, 
	APP_CLIENT_EMAIL 				VARCHAR2(150) NOT NULL, 
	APP_CLIENT_PHONE 				VARCHAR2(20) NOT NULL, 
	APP_CLIENT_ADDRESS 				VARCHAR2(200) NOT NULL, 
	APP_CLIENT_CITY 				VARCHAR2(100) NOT NULL, 
	APP_CLIENT_COUNTRY 				VARCHAR2(10) NOT NULL, 
	APP_CLIENT_ZIP 				VARCHAR2(12) NOT NULL,
	APP_CLIENT_ROLE 				VARCHAR2(1000) NOT NULL,
	STATUS NUMBER(1,0) DEFAULT 0,
	ACTIVE_FROM TIMESTAMP (6)	NOT NULL, 
	ACTIVE_TILL TIMESTAMP (6)	NOT NULL, 
	APP_CLIENT_ID     	VARCHAR2(50) NOT NULL,
	APP_CLIENT_ACCESS     	VARCHAR2(100) NOT NULL,
	APP_AUTH_USER     	VARCHAR2(50) NOT NULL,
	APP_AUTH_PASS     	VARCHAR2(100) NOT NULL,
	CREATED_BY    			VARCHAR2(20) NOT NULL,
	UPDATED_BY              VARCHAR2(20),
	CREATED_DATE 			TIMESTAMP (6)	NOT NULL, 
	UPDATED_DATE 			TIMESTAMP (6)
);

--------------------------------------------------------
--  Constraints for Table PG_ACTIVITY_LOG
--------------------------------------------------------

  ALTER TABLE "PG_ACTIVITY_LOG" ADD CONSTRAINT "PG_ACTIVITY_LOG_PK" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "PG_ACTIVITY_LOG" MODIFY ("ID" NOT NULL ENABLE);
 
  --ALTER TABLE "PG_ACTIVITY_LOG" MODIFY ("MTI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PG_BLACKLISTED_CARD
--------------------------------------------------------

  ALTER TABLE "PG_BLACKLISTED_CARD" ADD CONSTRAINT "PG_BLACKLISTED_CARD_PK" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "PG_BLACKLISTED_CARD" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PG_EMV_TRANSACTION
--------------------------------------------------------

  ALTER TABLE "PG_EMV_TRANSACTION" ADD CONSTRAINT "PG_EMV_TRANSACTION_PK" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "PG_EMV_TRANSACTION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PG_FEATURES
--------------------------------------------------------

  ALTER TABLE "PG_FEATURES" ADD CONSTRAINT "PG_FEATURES_PK" PRIMARY KEY ("FEATURE_ID") ENABLE;
 
  ALTER TABLE "PG_FEATURES" MODIFY ("FEATURE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PG_FEE_DETAIL
--------------------------------------------------------

  ALTER TABLE "PG_FEE_DETAIL" ADD CONSTRAINT "PG_FEE_DETAIL_PK" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "PG_FEE_DETAIL" MODIFY ("ID" NOT NULL ENABLE);


--------------------------------------------------------
--  Constraints for Table PG_MERCHANT_BANK
--------------------------------------------------------

  ALTER TABLE "PG_MERCHANT_BANK" ADD CONSTRAINT "PG_MERCHANT_BANK_PK" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "PG_MERCHANT_BANK" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PG_ROLE_FEATURE_MAPPING
--------------------------------------------------------

  ALTER TABLE "PG_ROLE_FEATURE_MAPPING" ADD CONSTRAINT "PG_ROLE_FEATURE_MAPPING_PK" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "PG_ROLE_FEATURE_MAPPING" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PG_ROLE_FEATURE_MAPPING" MODIFY ("ROLE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PG_ROLE_FEATURE_MAPPING" MODIFY ("FEATURE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PG_ROLE_FEATURE_MAPPING" MODIFY ("DISPLAY_ORDER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PG_SUB_FEATURES
--------------------------------------------------------

  ALTER TABLE "PG_SUB_FEATURES" ADD CONSTRAINT "PG_SUB_FEATURES_PK" PRIMARY KEY ("SUB_FEATURE_ID") ENABLE;
 
  ALTER TABLE "PG_SUB_FEATURES" MODIFY ("SUB_FEATURE_ID" NOT NULL ENABLE);
  
  ALTER TABLE "PG_SUB_FEATURES" MODIFY ("FEATURE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PG_SWITCH
--------------------------------------------------------

  ALTER TABLE "PG_SWITCH" ADD CONSTRAINT "PG_SWITCH_PK" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "PG_SWITCH" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PG_SWITCH" MODIFY ("SWITCH_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "PG_SWITCH" MODIFY ("SWITCH_TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PG_SWITCH_TRANSACTION
--------------------------------------------------------

  ALTER TABLE "PG_SWITCH_TRANSACTION" ADD CONSTRAINT "PG_SWITCH_TRANSACTION_PK" PRIMARY KEY ("ID") ENABLE;
 
 -- ALTER TABLE "PG_SWITCH_TRANSACTION" ADD CONSTRAINT "PG_SWITCH_TRANSACTION_UK1" UNIQUE ("TRANSACTION_ID") ENABLE;
 
  ALTER TABLE "PG_SWITCH_TRANSACTION" MODIFY ("ID" NOT NULL ENABLE);
 
  --ALTER TABLE "PG_SWITCH_TRANSACTION" MODIFY ("MTI" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table PG_TRANSACTION
--------------------------------------------------------

  ALTER TABLE "PG_TRANSACTION" ADD CONSTRAINT "PG_TRANSACTION_PK" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "PG_TRANSACTION" ADD CONSTRAINT "PG_TRANSACTION_UK1" UNIQUE ("TRANSACTION_ID") ENABLE;
 
  ALTER TABLE "PG_TRANSACTION" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PG_TRANSACTION" MODIFY ("MERCHANT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PG_TRANSACTION" MODIFY ("TERMINAL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PG_TRANSACTION" MODIFY ("ACQ_CHANNEL" NOT NULL ENABLE);
 
  ALTER TABLE "PG_TRANSACTION" MODIFY ("ACQ_TXN_MODE" NOT NULL ENABLE);
 
 -- ALTER TABLE "PG_TRANSACTION" MODIFY ("MTI" NOT NULL ENABLE);
 
 -- ALTER TABLE "PG_TRANSACTION" MODIFY ("PROC_CODE" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table PG_USER_ROLES
--------------------------------------------------------

  ALTER TABLE "PG_USER_ROLES" ADD CONSTRAINT "PG_USER_ROLES_PK" PRIMARY KEY ("ROLE_ID") ENABLE;
 
  ALTER TABLE "PG_USER_ROLES" MODIFY ("ROLE_ID" NOT NULL ENABLE);











--------------------------------------------------------
--  Ref Constraints for Table PG_MERCHANT_BANK
--------------------------------------------------------

--  ALTER TABLE "PG_MERCHANT_BANK" ADD CONSTRAINT "PG_MERCHANT_BANK_PG_MERCH_FK1" FOREIGN KEY ("MERCHANT_ID")
--	  REFERENCES "PG_MERCHANT" ("ID") ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table PG_ROLE_FEATURE_MAPPING
--------------------------------------------------------

  ALTER TABLE "PG_ROLE_FEATURE_MAPPING" ADD CONSTRAINT "PG_ROLE_FEATURE_MAPPING_P_FK1" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "PG_USER_ROLES" ("ROLE_ID") ENABLE;
 
  ALTER TABLE "PG_ROLE_FEATURE_MAPPING" ADD CONSTRAINT "PG_ROLE_FEATURE_MAPPING_P_FK2" FOREIGN KEY ("FEATURE_ID")
	  REFERENCES "PG_FEATURES" ("FEATURE_ID") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table PG_SUB_FEATURES
--------------------------------------------------------

  ALTER TABLE "PG_SUB_FEATURES" ADD CONSTRAINT "PG_SUB_FEATURES_PG_FEATUR_FK1" FOREIGN KEY ("FEATURE_ID")
	  REFERENCES "PG_FEATURES" ("FEATURE_ID") ENABLE;


-----------------------------------------------------------
--- Chatak TMS Tables
-----------------------------------------------------------
CREATE TABLE PG_COUNTRY (
  ID        				NUMBER(19) NOT NULL,
  NAME      				VARCHAR2(255) NOT NULL
);

ALTER TABLE PG_COUNTRY ADD CONSTRAINT PG_COUNTRY_PK PRIMARY KEY (ID);

CREATE TABLE PG_STATE (
  ID                    	NUMBER(20) NOT NULL,
  NAME                  	VARCHAR2(255) NOT NULL,
  STATUS                	VARCHAR2(255),
  COUNTRY_ID            	NUMBER(19)
  );
  
ALTER TABLE PG_STATE ADD CONSTRAINT PG_STATE_PK PRIMARY KEY (ID);
ALTER TABLE PG_STATE ADD FOREIGN KEY (COUNTRY_ID) REFERENCES PG_COUNTRY(ID);

CREATE TABLE PG_ADMIN_USER (
  ADMIN_USER_ID 				NUMBER(20) NOT NULL,
  USER_ROLE_ID 					NUMBER(5) NOT NULL,
  EMAIL 						VARCHAR2(100) NOT NULL,
  USER_NAME 					VARCHAR2(50) NOT NULL,
  FIRST_NAME 					VARCHAR2(50) NOT NULL,
  LAST_NAME 					VARCHAR2(50),
  PASSWORD 						VARCHAR2(200) NOT NULL,
  EMAIL_TOKEN 					VARCHAR2(255) DEFAULT '',
  EMAIL_VERIFIED 				NUMBER(1) DEFAULT 0,
  LANGUAGE 						VARCHAR2(10) DEFAULT '',
  ADDRESS1 						VARCHAR2(500) NOT NULL,
  ADDRESS2 						VARCHAR2(500) DEFAULT '',
  CITY 							VARCHAR2(50) DEFAULT '',
  STATE 						VARCHAR2(50) DEFAULT '',
  COUNTRY 						VARCHAR2(50) DEFAULT '',
  ZIP 							NUMBER(10),
  PHONE 						VARCHAR2(20),
  LAST_LOGIN_IP 				VARCHAR2(50) DEFAULT '',
  PREVIOUS_PASSWORDS 			VARCHAR2(1000),
  PASS_RETRY_COUNT	 			NUMBER(2) DEFAULT 0,
  STATUS 						NUMBER(1,0) DEFAULT 1,
  USER_TYPE 					VARCHAR2(20),
  SECURITY_QUESTION 			VARCHAR2(255),
  SECURITY_ANSWER 				VARCHAR2(255),
  SERVICE_TYPE 					NUMBER(5) ,
  CREATED_DATE 					TIMESTAMP NOT NULL,
  UPDATED_DATE 					TIMESTAMP,
  LAST_PASSWORD_CHANGE 			TIMESTAMP,
  LAST_LOGIN 					TIMESTAMP,
  CREATED_BY 					VARCHAR2(50) NOT NULL,
  UPDATED_BY 					VARCHAR2(50),
  REASON 						VARCHAR2(50)
);


ALTER TABLE PG_ADMIN_USER ADD CONSTRAINT ADMIN_USER_PK PRIMARY KEY (ADMIN_USER_ID);



CREATE TABLE PG_POS_DEVICE (
  ID 			        NUMBER(20) NOT NULL,
  DEVICE_SERIAL_NO 		VARCHAR2(255) NOT NULL,
  DEVICE_TYPE 			VARCHAR2(255) NOT NULL,
  DEVICE_MAKE 			VARCHAR2(255) NOT NULL,
  DEVICE_MODEL 			VARCHAR2(255) NOT NULL,
  STATUS 				VARCHAR2(255) NOT NULL,
  CREATED_BY 			VARCHAR2(20) NOT NULL,
  CREATED_DATE 			TIMESTAMP,
  UPDATED_BY 			VARCHAR2(20) DEFAULT NULL,
  UPDATED_DATE 			TIMESTAMP
);

ALTER TABLE PG_POS_DEVICE ADD CONSTRAINT PG_POS_DEVICE_PK PRIMARY KEY (ID);
CREATE SEQUENCE SEQ_PG_POS_DEVICE  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE;	

CREATE TABLE PG_TERMINAL_CAPABILITIES (
  TERMINAL_CAPABILITIES_ID    NUMBER(19) NOT NULL,
  ADMINISTRATIVE              NUMBER(1),
  ALPHANUMERIC_SPECIAL        NUMBER(1),
  CARD_CAPTURE                NUMBER(1),
  CASH                        NUMBER(1),
  CASH_DEPOSITS               NUMBER(1),
  CDA                         NUMBER(1),
  COMMAND_KEYS                NUMBER(1),
  DDA                         NUMBER(1),
  DISPLAY_ATTENDANT           NUMBER(1),
  DISPLAY_CARDHOLDER          NUMBER(1),
  ENCIPHERED_PIN_FOR_OFFLINE  NUMBER(1),
  ENCIPHERED_PIN_FOR_ONLINE   NUMBER(1),
  FINANCIAL_INSTITUTE         NUMBER(1),
  FUNCTION_KEYS               NUMBER(1),
  GOODS                       NUMBER(1),
  IC_WITH_CONTACTS            NUMBER(1),
  INQUIRY                     NUMBER(1),
  MAGNETIC_STRIPES            NUMBER(1),
  MANUAL_ENTRY_KEY            NUMBER(1),
  MERCHANT                    NUMBER(1),
  NO_CVM_REQUIRED             NUMBER(1),
  NUMERIC_KEYS                NUMBER(1),
  PAYMENT                     NUMBER(1),
  PLAIN_TEXT_PIN_FOR_ICC      NUMBER(1),
  PRINT_ATTENDANT             NUMBER(1),
  PRINT_CARDHOLDER            NUMBER(1),
  SDA                         NUMBER(1),
  SERVICES                    NUMBER(1),
  SIGNATURE                   NUMBER(1),
  TRANSFER                    NUMBER(1),
  PARAMETER_TYPE              VARCHAR2(255),
  CREATED_BY                  VARCHAR2(20) NOT NULL,
  UPDATED_BY                  VARCHAR2(20),
  CREATED_DATE                TIMESTAMP NOT NULL,
  UPDATED_DATE                TIMESTAMP
  );
  
ALTER TABLE PG_TERMINAL_CAPABILITIES ADD CONSTRAINT PG_TERMINAL_CAPABILITIES_PK PRIMARY KEY (TERMINAL_CAPABILITIES_ID);  

CREATE SEQUENCE SEQ_PG_TERMINAL_CAPABILITIES  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE;	

CREATE TABLE PG_PARAMETER_PROFILE (
  PROFILE_ID                    NUMBER(19) NOT NULL,
  ATTENDED                      VARCHAR2(255),  
  CURRENCY_CODE                 VARCHAR2(255),
  DEFAULT_CDOL                  VARCHAR2(255),  
  DEFAULT_DDOL                  VARCHAR2(255),  
  DEFAULT_TDOL                  VARCHAR2(255),
  ISO_COUNTRY_CODE              VARCHAR2(255),
  LOCAL_CURRENCY_CODE           VARCHAR2(255),
  MAXT_TARGET_PERCENTAGE        VARCHAR2(255),
  PROFILE_NAME                  VARCHAR2(255),
  STATUS                        VARCHAR2(255),
  TARGET_PERCENTAGE             VARCHAR2(255),
  TERMINAL_FLOOR_LIMIT          VARCHAR2(255),
  TERMINAL_TYPE                 VARCHAR2(255),
  UNATTENDED                    VARCHAR2(255),
  TERMINAL_CAPABILITIES_ID      NUMBER(19) NOT NULL,
  FINANCIAL_INSTITUTE           NUMBER(1),
  MERCHANT                      NUMBER(1),
  ADMINISTRATIVE                VARCHAR2(255),
  ALPHANUMERIC_SPECIAL_CHAR     VARCHAR2(255),
  CARD_CAPTURE                  VARCHAR2(255),
  CASH                          VARCHAR2(255),
  CASH_DEPOSITS                 VARCHAR2(255),
  CDA                           VARCHAR2(255),
  COMMAND_KEYS                  VARCHAR2(255),
  DDA                           VARCHAR2(255),
  DISPLAY_ATTENDANT             VARCHAR2(255),
  DISPLAY_CARDHOLDER            VARCHAR2(255),
  ENCIPHERED_PIN_FOR_OFFLINE    VARCHAR2(255),
  ENCIPHERED_PIN_FOR_ONLINE     VARCHAR2(255),
  FUNCTION_KEYS                 VARCHAR2(255),
  GOODS                         VARCHAR2(255),
  IC_WITH_CONTACTS              VARCHAR2(255),
  INQUIRY                       VARCHAR2(255),
  MAGNETIC_STRIPES              VARCHAR2(255),
  MANUAL_ENTRY_KEY              VARCHAR2(255),
  NO_CVM_REQUIRED               VARCHAR2(255),
  NUMERIC_KEYS                  VARCHAR2(255),
  OPERATED_BY                   VARCHAR2(255),
  PAYMENT                       VARCHAR2(255),
  PLAIN_TEXT_PIN_FOR_ICC        VARCHAR2(255),
  PRINT_ATTENDANT               VARCHAR2(255),
  PRINT_CARDHOLDER              VARCHAR2(255),
  SDA                           VARCHAR2(255),
  SERVICES                      VARCHAR2(255),
  SIGNATURE                     VARCHAR2(255),
  TRANSFER                      VARCHAR2(255),
  ATTEND_FINANCIAL_INSTITUTE    NUMBER(1),
  ATTEND_MERCHANT               NUMBER(1),
  UNATTEND_MERCHANT             NUMBER(1),
  UNATTEND_FINANCIAL_INSTITUTE  NUMBER(1),
  PARAMETER_TYPE                VARCHAR2(255),
  REASON                        VARCHAR2(250) DEFAULT '',
  CREATED_BY                    VARCHAR2(255) NOT NULL,
  CREATED_DATE                  TIMESTAMP NOT NULL,  
  UPDATED_BY                    VARCHAR2(255),
  UPDATED_DATE                  TIMESTAMP
  );
  
ALTER TABLE PG_PARAMETER_PROFILE ADD CONSTRAINT PG_PARAMETER_PROFILE_PK PRIMARY KEY (PROFILE_ID);  
ALTER TABLE PG_PARAMETER_PROFILE ADD FOREIGN KEY (TERMINAL_CAPABILITIES_ID) REFERENCES PG_TERMINAL_CAPABILITIES(TERMINAL_CAPABILITIES_ID);  

ALTER TABLE PG_PARAMETER_PROFILE add UNATTEND_CARDHOLDER NUMBER(1);

CREATE SEQUENCE SEQ_PG_PARAMETER_PROFILE  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE;	

CREATE TABLE PG_PAN_LENGTH (
  PAN_LENGTH_ID NUMBER(20) NOT NULL,
  PAN_LENGTH NUMBER(20) NOT NULL,
  CREATED_BY varchar(20) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL
);

ALTER TABLE PG_PAN_LENGTH ADD CONSTRAINT PG_PAN_LENGTH_PK PRIMARY KEY (PAN_LENGTH_ID);

CREATE TABLE PG_PARAMETER_MAGSTRIPE (
  MAGSTRIPE_ID 				NUMBER(20) NOT NULL,
  CARD_LABEL 				VARCHAR2(255),
  CARD_RANGE_HIGH 			NUMBER(20),
  CARD_RANGE_LOW 			NUMBER(20),
  MAGSTRIPE_NAME 			VARCHAR2(255) NOT NULL,
  PAN_LENGTH 				VARCHAR2(255),
  STATUS 					VARCHAR2(255) NOT NULL,
  CREATED_BY 				VARCHAR2(20) NOT NULL,
  CREATED_DATE 				TIMESTAMP,
  UPDATED_BY 				VARCHAR2(20) DEFAULT NULL,
  UPDATED_DATE 				TIMESTAMP
);

ALTER TABLE PG_PARAMETER_MAGSTRIPE ADD CONSTRAINT PG_PARAMETER_MAGSTRIPE_PK PRIMARY KEY (MAGSTRIPE_ID);

CREATE SEQUENCE SEQ_PG_PARAMETER_MAGSTRIPE  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE;	

CREATE TABLE PG_ACTION_CODE_PARAMETERS (
  ACTION_CODE_ID 				NUMBER(20) NOT NULL,
  ACTION_CODE_NAME 				VARCHAR2(255),
  CREATED_BY 					VARCHAR2(255) NOT NULL,
  CREATED_DATE 					TIMESTAMP NOT NULL
);

ALTER TABLE PG_ACTION_CODE_PARAMETERS ADD CONSTRAINT PG_ACTION_CODE_PARAMETERS_PK PRIMARY KEY (ACTION_CODE_ID);  

CREATE TABLE PG_AID (
  APPLICATION_ID 				NUMBER(11) NOT NULL,
  APPLICATION_NAME 				VARCHAR2(255),
  CREATED_BY 					VARCHAR2(255) NOT NULL,
  CREATED_DATE 					TIMESTAMP NOT NULL
);

ALTER TABLE PG_AID ADD CONSTRAINT PG_AID_PK PRIMARY KEY (APPLICATION_ID);  

CREATE TABLE PG_CA_PUBLIC_KEYS (
  PUBLIC_KEY_ID 				NUMBER(11) NOT NULL,
  PUBLIC_KEY_NAME 				VARCHAR2(255),
  CREATED_BY 					VARCHAR2(20) NOT NULL,
  CREATED_DATE 					TIMESTAMP NOT NULL
 );

 ALTER TABLE PG_CA_PUBLIC_KEYS ADD CONSTRAINT PG_CA_PUBLIC_KEYS_PK PRIMARY KEY (PUBLIC_KEY_ID);  
 
 
CREATE TABLE PG_ISO_COUNTRY_CODE (
  ID 							NUMBER(20) NOT NULL,
  CODE 							VARCHAR2(255),
  NAME 							VARCHAR2(255),
  CREATED_BY 					VARCHAR2(20) NOT NULL,
  CREATED_DATE 					TIMESTAMP NOT NULL
);

ALTER TABLE PG_ISO_COUNTRY_CODE ADD CONSTRAINT PG_ISO_COUNTRY_CODE_PK PRIMARY KEY (ID);  

CREATE TABLE PG_LOCAL_CURRENCY_CODE (
  ID 							NUMBER(20) NOT NULL,
  COUNTRY_ID 					NUMBER(20),
  CODE 							VARCHAR2(255),
  CREATED_BY 					VARCHAR2(20) NOT NULL,
  CREATED_DATE 					TIMESTAMP NOT NULL
);

ALTER TABLE PG_LOCAL_CURRENCY_CODE ADD CONSTRAINT PG_LOCAL_CURRENCY_CODE_PK PRIMARY KEY (ID);  

CREATE TABLE PG_CURRENCY_CODE (
  ID 							NUMBER(20) NOT NULL,
  COUNTRY_ID 					NUMBER(20),
  CODE 							VARCHAR2(255),
  CREATED_BY 					VARCHAR2(20) NOT NULL,
  CREATED_DATE 					TIMESTAMP NOT NULL
);

ALTER TABLE PG_CURRENCY_CODE ADD CONSTRAINT PG_CURRENCY_CODE_PK PRIMARY KEY (ID);  

CREATE TABLE PG_TERMINAL (
  ID 			NUMBER(20) NOT NULL,
  COMMENTS 						VARCHAR2(255), 
  MERCHANT_ID 					NUMBER(20),
  PRICE 						NUMBER(20),
  STATUS 						VARCHAR2(255) NOT NULL,
  TERMINAL_ID 					NUMBER(20) NOT NULL,
  DESCRIPTION 					VARCHAR2(255),
  PRODUCT_ID 					VARCHAR2(255),
  CREATED_BY                  	VARCHAR2(20) NOT NULL,
  UPDATED_BY                  	VARCHAR2(20),
  CREATED_DATE                	TIMESTAMP NOT NULL,
  UPDATED_DATE                	TIMESTAMP
);

ALTER TABLE PG_TERMINAL ADD CONSTRAINT PG_TERMINAL_PK1 PRIMARY KEY (ID); 


CREATE TABLE PG_DEVICE_MANAGEMENT (
  DEVICE_MANAGEMENT_ID 			NUMBER(20) NOT NULL,
  POS_DEVICE_ID 				NUMBER(20),
  IMEI_NO 						VARCHAR2(255),
  APPLICATION_ID 				VARCHAR2(255),
  MAGNETIC_STRIPE_PARAMETERS 	VARCHAR2(255),
  CA_PUBLIC_KEYS 				VARCHAR2(255),
  ACTION_CODE_PARAMETERS 		VARCHAR2(255),
  STAN_NUMBER 					VARCHAR2(255),
  INVOICE_NUMBER 				VARCHAR2(255),
  BATCH_NUMBER 					VARCHAR2(255),
  TIP_PERCENTAGE 				VARCHAR2(255),
  JUST_ALLOWED 					VARCHAR2(255),
  REFUND_ALLOWED 				VARCHAR2(255),
  PREAUTH_ALLOWED 				VARCHAR2(255),
  TIP_ALLOWED 					VARCHAR2(255),
  PROFILE_ID 					NUMBER(20) NOT NULL,
  STATUS 						VARCHAR2(255) NOT NULL,
  TERMINAL_CONFIG_PROFILE 		VARCHAR2(255),
  TERMINAL_ID 					NUMBER(20) NOT NULL,
  REMARKS 						VARCHAR2(255),
  CREATED_BY                  	VARCHAR2(20) NOT NULL,
  UPDATED_BY                  	VARCHAR2(20),
  CREATED_DATE                	TIMESTAMP NOT NULL,
  UPDATED_DATE                	TIMESTAMP
 );

ALTER TABLE PG_DEVICE_MANAGEMENT ADD CONSTRAINT PG_MOBILE_DEVICE_MGMT_PK PRIMARY KEY (DEVICE_MANAGEMENT_ID);  
ALTER TABLE PG_DEVICE_MANAGEMENT ADD FOREIGN KEY (PROFILE_ID) REFERENCES PG_PARAMETER_PROFILE(PROFILE_ID);  
ALTER TABLE PG_DEVICE_MANAGEMENT ADD FOREIGN KEY (TERMINAL_ID) REFERENCES PG_TERMINAL(ID);  


CREATE SEQUENCE SEQ_PG_MOBILE_DEVICE_MGMT  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE;	


---------------------------------------------------------
--Merchant, Fee program tables
---------------------------------------------------------

--------------------------------------------------------
--  DDL for Sequence SEQ_PG_FEE_PROGRAM
--------------------------------------------------------

CREATE SEQUENCE  SEQ_PG_FEE_PROGRAM  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;


--------------------------------------------------------
--  DDL for Table PG_FEE_PROGRAM
--------------------------------------------------------

CREATE TABLE PG_FEE_PROGRAM 
(	
	FEE_PROGRAM_ID 			    NUMBER(20,0)    NOT NULL ENABLE, 
	FEE_PROGRAM_NAME 			VARCHAR2(50), 
	FEE_PROGRAM_DESC 			VARCHAR2(255),
    PROCESSOR                   VARCHAR2(20),
	REASON 		  			    VARCHAR2(255),
	CREATED_BY    				VARCHAR2(20)    NOT NULL,
	UPDATED_BY                  VARCHAR2(20),
	CREATED_DATE				TIMESTAMP (6)	NOT NULL, 
	UPDATED_DATE 				TIMESTAMP (6), 
	STATUS 					    VARCHAR2(20));
 
ALTER TABLE PG_FEE_PROGRAM ADD CONSTRAINT FEE_PROGRAM_PK PRIMARY KEY (FEE_PROGRAM_ID);


--------------------------------------------------------
--  DDL for Sequence SEQ_PG_FEE_PROGRAM_VALUE
--------------------------------------------------------
CREATE SEQUENCE  SEQ_PG_FEE_PROGRAM_VALUE  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Table PG_FEE_PROGRAM_VALUE
--------------------------------------------------------

CREATE TABLE PG_FEE_PROGRAM_VALUE 
(	
	FEE_PROGRAM_VALUE_ID 	NUMBER(20,0) NOT NULL ENABLE,
	FEE_CODE 				NUMBER(20,0) NOT NULL ENABLE, 
	FEE_PROGRAM_ID 			NUMBER(20,0), 
	FEE_MAX_VALUE 			NUMBER(20,0), 
	FEE_MIN_VALUE 			NUMBER(20,0), 
	FEE_PERCENTAGE_ONLY 	DECIMAL(20,0),
	CREATED_BY    			VARCHAR2(20) NOT NULL,
	UPDATED_BY              VARCHAR2(20),
	CREATED_DATE 			TIMESTAMP (6)	NOT NULL, 
	UPDATED_DATE 			TIMESTAMP (6)
) ;

ALTER TABLE PG_FEE_PROGRAM_VALUE ADD CONSTRAINT FEE_PROGRAM_VALUE_PK PRIMARY KEY (FEE_PROGRAM_VALUE_ID);
ALTER TABLE PG_FEE_PROGRAM_VALUE ADD CONSTRAINT PG_FEE_PROGRAM_VALUE_PG_F_FK1 FOREIGN KEY (FEE_PROGRAM_ID) REFERENCES PG_FEE_PROGRAM (FEE_PROGRAM_ID) ENABLE;

--------------------------------------------------------
--  DDL for Sequence PG_SEQ_FEE_CODE
--------------------------------------------------------

CREATE SEQUENCE  PG_SEQ_FEE_CODE  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;


--------------------------------------------------------
--  DDL for Table PG_FEE_CODE
--------------------------------------------------------

CREATE TABLE PG_FEE_CODE
(	
	FEE_CODE 					NUMBER(20,0), 
	FEE_SHORT_CODE 				VARCHAR2(255), 
	PROC_CODE_TXN_TYPE 			VARCHAR2(10), 
	RESPONSE_CODE 				VARCHAR2(10),
	FEE_DESCRIPTION 			VARCHAR2(255)
);

------------------------------------------------------
--03/03/15 added DDL for merchant 
------------------------------------------------------


--------------------------------------------------------
--  DDL for Sequence SEQ_PG_MERCHANT_CONFIG
--------------------------------------------------------

 CREATE SEQUENCE  SEQ_PG_MERCHANT_CONFIG  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;


--------------------------------------------------------
--  DDL for Table PG_MERCHANT_CONFIG
--------------------------------------------------------
  
    CREATE TABLE "PG_MERCHANT_CONFIG" 
   (	"MER_CONFIG_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"FEE_PROGRAM" VARCHAR2(100 BYTE), 
	"PROCESSOR" VARCHAR2(100 BYTE), 
	"REFUND" NUMBER(1,0), 
	"TIP_AMOUNT" NUMBER(1,0), 
	"TAX_AMOUNT" NUMBER(1,0), 
	"SHIPPING_AMT" NUMBER(1,0), 
	"ALLOW_REPEAT_SALE" NUMBER(1,0), 
	"SHOW_RECURRING_BILLING" NUMBER(1,0), 
	"AUTO_SETTLEMENT" NUMBER(1,0), 
	"CREATED_DATE" TIMESTAMP (6), 
	"UPDATED_DATE" TIMESTAMP (6), 
	 CONSTRAINT "PG_MERCHANT_CONFIG_PK" PRIMARY KEY ("MER_CONFIG_ID")
   );
 
 ------------------------------------------------------
--10/03/15 added DDL for merchant users And updated pgmerchant script
------------------------------------------------------

 --------------------------------------------------------
--  DDL for Sequence SEQ_PG_MERCHANT_CONFIG
--------------------------------------------------------

 CREATE SEQUENCE  "SEQ_PG_MERCHANT_USERS"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
 
 
--------------------------------------------------------
--  DDL for Table PG_MERCHANT_USERS
--------------------------------------------------------
 
 
   CREATE TABLE "PG_MERCHANT_USERS" 
   (	"ID" NUMBER(15,0) NOT NULL ENABLE, 
	"USER_NAME" VARCHAR2(100 BYTE), 
	"P_PASSWORD" VARCHAR2(200 BYTE), 
	"STATUS" NUMBER(1,0) DEFAULT 0, 
	"CREATED_DATE" TIMESTAMP (6), 
	"UPDATED_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"UPDATED_BY" VARCHAR2(50 BYTE), 
	"USER_TYPE" VARCHAR2(100 BYTE), 
	 CONSTRAINT "PG_MERCHANT_USERS_PK" PRIMARY KEY ("ID")
 
   ) ;
   
 --------------------------------------------------------
--  DDL for Table PG_MERCHANT
--------------------------------------------------------
 
  CREATE TABLE "PG_MERCHANT" 
   (	"ID" NUMBER(15,0) NOT NULL ENABLE, 
	"BUSINESS_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"PHONE" NUMBER(13,0), 
	"FAX" NUMBER(13,0), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"ADDRESS1" VARCHAR2(60 BYTE), 
	"ADDRESS2" VARCHAR2(60 BYTE), 
	"CITY" VARCHAR2(60 BYTE), 
	"STATE" VARCHAR2(60 BYTE), 
	"COUNTRY" VARCHAR2(60 BYTE), 
	"PIN" NUMBER(10,0),
	"TIN" VARCHAR2(20), 
	"SSN" VARCHAR2(20),
	"TIMEZONE" VARCHAR2(50 BYTE), 
	"APPLICATION_MODE" VARCHAR2(50 BYTE), 
	"USER_NAME" VARCHAR2(50 BYTE), 
	"BUSINESS_URL" VARCHAR2(200 BYTE), 
	"FEDERAL_TAX_ID" VARCHAR2(50 BYTE), 
	"STATE_TAX_ID" VARCHAR2(50 BYTE), 
	"SALES_TAX_ID" VARCHAR2(50 BYTE), 
	"OWNERSHIP" VARCHAR2(50 BYTE), 
	"ESTIMATED_YEAR_SALE" NUMBER(16,0), 
	"STATUS" NUMBER(1,0), 
	"BUSINESS_START_DATE" DATE, 
	"NO_OF_EMPLOYEE" NUMBER(10,0), 
	"ROLE" VARCHAR2(50 BYTE), 
	"CREATED_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATED_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"MER_CONFIG_ID" NUMBER(15,0), 
	"MERCHANT_CODE" VARCHAR2(50 BYTE), 
	"MERCHANT_USER_ID" NUMBER(15,0), 
	"MCC" VARCHAR2(20), 
	"DAILY_TXN_LIMIT" NUMBER(16,0), 
	"ALLOW_INTERNATIONAL_TXN" NUMBER(1,0) DEFAULT 0, 
	"MERCHANT_TYPE" VARCHAR2(50),
	"VALID_FROM_DATE" TIMESTAMP (6), 
	"VALID_TO_DATE" TIMESTAMP (6), 
	 CONSTRAINT "PG_MERCHANT1_PK" PRIMARY KEY ("ID"), 
	 CONSTRAINT "PG_MERCHANT_FK1" FOREIGN KEY ("MER_CONFIG_ID")
	  REFERENCES "PG_MERCHANT_CONFIG" ("MER_CONFIG_ID") ENABLE, 
	 CONSTRAINT "PG_MERCHANT_FK2" FOREIGN KEY ("MERCHANT_USER_ID")
	  REFERENCES "PG_MERCHANT_USERS" ("ID") ENABLE
   ) ;
  
--------------------------------------------------------
--  DDL for Table PG_RECURRING_CUSTOMER_INFO
--------------------------------------------------------
 
CREATE TABLE PG_RECURRING_CUSTOMER_INFO 
(
  RECURRING_CUSTOMER_INFO_ID NUMBER NOT NULL 
, CUSTOMER_ID VARCHAR2(50) NOT NULL 
, FIRST_NAME VARCHAR2(50) NOT NULL 
, LAST_NAME VARCHAR2(50) NOT NULL 
, EMAIL_ID VARCHAR2(50) 
, MOBILE_NUMBER VARCHAR2(20) 
, WORK_PHONE VARCHAR2(20) 
, FAX VARCHAR2(20) 
, ADDRESS1 VARCHAR2(255) 
, ADDRESS2 VARCHAR2(255) 
, ADDRESS3 VARCHAR2(255) 
, AREA VARCHAR2(50) 
, CITY VARCHAR2(20) 
, STATE VARCHAR2(20) 
, COUNTRY VARCHAR2(20) 
, ZIPCODE VARCHAR2(20)
,STATUS VARCHAR2(20) DEFAULT NULL
, CREATED_DATE DATE 
, UPDATED_DATE DATE 
, CREATED_BY VARCHAR2(20) NOT NULL 
, UPDATED_BY VARCHAR2(20) 
, CONSTRAINT RECURRING_CUSTOMER_INFO_PK PRIMARY KEY ("RECURRING_CUSTOMER_INFO_ID")
);

------------Sequences--------------------------------------------
CREATE SEQUENCE "SEQ_PG_RECURR_CUST_INFO_ID" MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE NOORDER NOCYCLE ;

---------------------------------------------------------------------------------------------------------
CREATE TABLE PG_RECURRING_PAYMENT_INFO 
(
 RECURRING_PAYMENT_INFO_ID  NUMBER(20)  NOT NULL,
    RECURRING_CUSTOMER_INFO_ID   NUMBER(20)  NOT NULL,
    CREDIT_CARD_TYPE          VARCHAR2(50) NOT NULL,
    CARD_NUMBER               VARCHAR2(255) DEFAULT NULL,
    EXP_DT                    VARCHAR2(10)  DEFAULT NULL,
    NAME_ON_CARD              VARCHAR2(50)  DEFAULT NULL,
    STREET_ADDRESS            VARCHAR2(255) DEFAULT NULL,
    ZIP_CODE                  VARCHAR2(20) DEFAULT NULL,
    IMMIDIATE_CHARGE          VARCHAR2(5) DEFAULT NULL,
    CREATED_DATE              TIMESTAMP,
    UPDATED_DATE              TIMESTAMP,
    CREATED_BY         VARCHAR2(20) NOT NULL,
    UPDATED_BY                VARCHAR2(20)
);


ALTER TABLE PG_RECURRING_PAYMENT_INFO 
ADD (STATUS VARCHAR2(20) );

ALTER TABLE PG_RECURRING_PAYMENT_INFO 
ADD (AMOUNT VARCHAR2(50) );

------------Sequences--------------------------------------------
CREATE SEQUENCE "SEQ_PG_RECURR_PAYMT_INFO_ID" MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE NOORDER NOCYCLE ;

---------------------------------------------------------------------------------------------------------
CREATE TABLE PG_RECURRING_CONTRACT_INFO 
(
  RECURRING_CONTRACT_INFO_ID   NUMBER(20)  NOT NULL,
  CONTRACT_ID                  VARCHAR2(50)  NOT NULL,
  CONTRACT_NAME                VARCHAR2(50)  NOT NULL,
  START_DATE                   TIMESTAMP,
  END_DATE                     TIMESTAMP,
  CONTACT_AMOUNT               NUMBER(10,2),
  TAX                          NUMBER(10,2),
  STATUS                       VARCHAR2(20),
  CONTRACT_EXECUTION           VARCHAR2(20),
  RECURRING_PAYMENT_INFO_ID    NUMBER(20),
  TRANSACTION_APPROVED_EMAIL   VARCHAR2(10),
  TRANSACTION_DECLINED_EMAIL   VARCHAR2(10),
  CREATED_DATE                 TIMESTAMP,
  UPDATED_DATE                 TIMESTAMP,
  CREATED_BY                 VARCHAR2(20) NOT NULL,
  UPDATED_BY                   VARCHAR2(20)
);


ALTER TABLE PG_RECURRING_CONTRACT_INFO  
MODIFY (CONTRACT_ID NULL);


ALTER TABLE PG_RECURRING_CONTRACT_INFO 
ADD (LAST_BILL_DATE TIMESTAMP(6) );
------------Sequences--------------------------------------------
CREATE SEQUENCE "SEQ_PG_RECURR_CONTRA_INFO_ID" MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE NOORDER NOCYCLE ;
-----------------------------------------------------------------

  
--03/05/15 added Alter script for user and role management
------------------------------------------------------

ALTER TABLE PG_ROLE_FEATURE_MAPPING ADD (SUB_FEATURE_ID NUMBER(10)) ;

--------------------------------------------------------
--  DDL for Table PG_FRAUD_BASIC
--------------------------------------------------------
  
  CREATE TABLE "PG_FRAUD_BASIC" 
   (	"ID" NUMBER(15,0) NOT NULL ENABLE, 
	"DENIED_IP" VARCHAR2(2000 BYTE), 
	"DENIED_EMAIL" VARCHAR2(2000 BYTE), 
	"DENIED_BIN" VARCHAR2(2000 BYTE), 
	"DENIED_COUNTRY" VARCHAR2(2000 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"UPDATED_DATE" TIMESTAMP (6), 
	"MERCHANT_ID" NUMBER(20,0), 
	 CONSTRAINT "PG_FRAUD_BASIC_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "PG_FRAUD_BASIC_FK1" FOREIGN KEY ("MERCHANT_ID")
	  REFERENCES "PG_MERCHANT" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  
  CREATE TABLE "PG_MAGNETIC_STRIPE_PARAMETERS" 
   (	"MAGNETIC_STRIPE_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"MAGNETIC_STRIPE_NAME" VARCHAR2(255 BYTE), 
	"CREATED_BY" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CREATED_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "PG_MAGNETIC_STRIPE_PARAMS_PK" PRIMARY KEY ("MAGNETIC_STRIPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  ALTER TABLE "PG_MERCHANT_USERS"
   ADD (

	"EMAIL_TOKEN" VARCHAR2(255 BYTE) DEFAULT '', 
	"EMAIL_VERIFIED" NUMBER(1,0) DEFAULT 0, 
	"LAST_LOGIN_IP" VARCHAR2(50 BYTE) DEFAULT '', 
	"PREVIOUS_PASSWORDS" VARCHAR2(1000 BYTE), 
	"PASS_RETRY_COUNT" NUMBER(2,0) DEFAULT 0, 
	"SECURITY_QUESTION" VARCHAR2(255 BYTE), 
	"SECURITY_ANSWER" VARCHAR2(255 BYTE), 
	"SERVICE_TYPE" NUMBER(5,0), 
	"LAST_PASSWORD_CHANGE" TIMESTAMP (6), 
	"LAST_LOGIN" TIMESTAMP (6), 
	"REASON" VARCHAR2(50 BYTE)

	);
	
	Alter table pg_user_roles add "STATUS" NUMBER(1,0) DEFAULT 0;
	
	-- Modify the column
	ALTER TABLE PG_TRANSACTION MODIFY INVOICE_NUMBER VARCHAR2(20);

 
--28/04/2015 PG_Account--to create merchant account and balance---
-----------------------------------------------------
--  DDL for Sequence SEQ_PG_ACCOUNT
--------------------------------------------------------
CREATE SEQUENCE  "SEQ_PG_ACCOUNT"  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Table PG_ACCOUNT
--------------------------------------------------------
  CREATE TABLE "PG_ACCOUNT" 
   (	
   "ID" NUMBER(10,0), 
	"ENTITY_ID" VARCHAR2(50) not null, 
	"ENTITY_TYPE" VARCHAR2(50) not null,
	"ACCOUNT_DESC" VARCHAR2(100),
	"CATEGORY" VARCHAR2(100),
	"CURRENT_BALANCE" NUMBER(20,0) default 0,
	"AVAILABLE_BALANCE" NUMBER(20,0) default 0,
	"CURRENCY" VARCHAR2(20) default 'USD',
	"AUTO_PAYMENT_LIMIT" NUMBER(20,0),
	"AUTO_PAYMENT_METHOD" VARCHAR2(20),
	"AUTO_TRANSFER_DAY" VARCHAR2(100),
	"STATUS" VARCHAR2(20),
  	"CREATED_DATE"  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 	"UPDATED_DATE"  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
   ) ;
   
-----------------------------------------------------
--  DDL for Sequence SEQ_PG_MERCHANT_SETTLEMENT
--------------------------------------------------------
CREATE SEQUENCE  "SEQ_PG_MERCHANT_SETTLEMENT"  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table PG_MERCHANT_SETTLEMENT
--------------------------------------------------------
  CREATE TABLE "PG_MERCHANT_SETTLEMENT" 
   (	
    "ID" NUMBER(10,0), 
	"MERCAHNT_CODE" VARCHAR2(50), 
	"ACCOUNT_NUMBER" VARCHAR2(50),
	"AMOUNT" NUMBER(20,0),
	"STATUS" VARCHAR2(20),
	"CREATED_BY" NUMBER(10,0), 
	"UPDATED_BY" NUMBER(10,0),
	"REQUESTED_DATE"  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 	"UPDATED_DATE"  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
   ) ;
   
   ALTER table PG_TRANSACTION add "MERCHANT_SETTLEMENT_ID" NUMBER(10,0);
   ALTER table PG_TRANSACTION add "MERCHANT_SETTLEMENT_STATUS" varchar2(20);
   
   
--05/05/15 added alter script and create script to store token detail
   
   ALTER table PG_ACCOUNT add "ACCOUNT_NUM" NUMBER(20,0);
   ALTER table PG_MERCHANT add "MERCHANT_CALLBACK_URL" VARCHAR2(100); 
  
-----------------------------------------------------
--  DDL for Sequence SEQ_PG_CARD_TOKEN_DETAILS
--------------------------------------------------------
CREATE SEQUENCE  "SEQ_PG_CARD_TOKEN_DETAILS"  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------

CREATE TABLE PG_CARD_TOKEN_DETAILS
   (   
   "ID" NUMBER(20,0),
   "CARD_USER_EMAIL" VARCHAR2(150) NOT NULL,
   "CARD_TOKEN" VARCHAR2(100) NOT NULL,
   "CARD_TYPE" VARCHAR2(10) NOT NULL,
   "CARD_TOKEN_EXP_DATE" VARCHAR2(40) NOT NULL,
   "CARD_LAST_FOUR" VARCHAR2(4) NOT NULL,
   "CREATED_DATE"  TIMESTAMP DEFAULT CURRENT_TIMESTAMP   
  );

-- ALTER table PG_MERCHANT_BANK drop column MERCHANT_ID;
-- ALTER table PG_MERCHANT_BANK add MERCHANT_CODE varchar(20);


--14/05/15 added alter script for Genesys changes
alter table PG_ONLINE_TXN_LOG add "INVOICE_NUMBER" varchar2(20);
alter table PG_ONLINE_TXN_LOG add "REGISTER_NUMBER" varchar2(20);
alter table PG_ONLINE_TXN_LOG add "TXN_FEE_AMOUNT" NUMBER(10,0);
alter table PG_ONLINE_TXN_LOG add "CARD_HOLDER_NAME" varchar2(20);
alter table PG_ONLINE_TXN_LOG add "TXN_PAYMENT_PROCESS_TYPE" NUMBER(1,0);
alter table PG_ACCOUNT add "FEE_BALANCE" NUMBER(20,0) DEFAULT 0;


ALTER table PG_TRANSACTION add "MERCHANT_FEE_AMOUNT" NUMBER(10,0);
ALTER table PG_TRANSACTION add "TXN_DESCRIPTION" varchar2(500);

alter table "PG_TRANSACTION" add "REASON" VARCHAR2(500 BYTE);

--26/05/15 added for pos entry mode
alter table "PG_ONLINE_TXN_LOG" add "POS_ENTRY_MODE" varchar2(50);
alter table "PG_ONLINE_TXN_LOG" modify  "MERCHANT_AMOUNT" NUMBER(12,0);
alter table "PG_ONLINE_TXN_LOG" modify  "TXN_TOTAL_AMOUNT" NUMBER(12,0);
alter table "PG_ONLINE_TXN_LOG" modify  "TXN_FEE_AMOUNT" NUMBER(12,0);
alter table "PG_SWITCH_TRANSACTION" modify  "TXN_AMOUNT" NUMBER(14,2);
alter table "PG_ONLINE_TXN_LOG" add "MERCHANT_NAME" VARCHAR2(100 BYTE);
alter table "PG_ONLINE_TXN_LOG" modify "BILLER_COUNTRY" VARCHAR2(50 BYTE);
alter table "PG_ONLINE_TXN_LOG" modify "CARD_HOLDER_NAME" VARCHAR2(50 BYTE);

CREATE SEQUENCE "SEQ_PG_BIN_RANGE" MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE ;
CREATE TABLE "PG_BIN_RANGE"
    (
      "ID"           NUMBER(10,0) PRIMARY KEY ,
      "BIN"          NUMBER(6)UNIQUE,
      "CREATED_DATE" TIMESTAMP (6),
      "STATUS"       NUMBER(1,0)
    );


CREATE SEQUENCE "SEQ_PG_SPLIT_TRANSACTION"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
CREATE TABLE "PG_SPLIT_TRANSACTION"
    (
      "ID"                    NUMBER(10,0) PRIMARY KEY ,
      "SPLIT_TRANSACTION_ID"  NUMBER(12,0),
      "PG_TRANSACTION_ID"     NUMBER(12,0),
      "PG_REF_TRANSACTION_ID" NUMBER(12,0),
      "SPLIT_AMOUNT"          NUMBER(20,0),
      "TOTAL_AMOUNT"          NUMBER(20,0),
      "MERCHANT_ID"           NUMBER(15,0),
      "SPLIT_MODE"            VARCHAR2(20 BYTE),
      "CREATED_DATE"          TIMESTAMP (6),
      "UPDATED_DATE"          TIMESTAMP (6),
      "STATUS"                NUMBER(1,0),
      "CARD_HOLDER_NAME"      VARCHAR2(150 BYTE),
      "PAN"                   VARCHAR2(150 BYTE),
      "PAN_MASKED"            VARCHAR2(20 BYTE),
      "EXP_DATE"              VARCHAR2(50 BYTE),
      "TXN_DESCRIPTION"       VARCHAR2(500 BYTE),
      "REASON"                VARCHAR2(500 BYTE)
    );


ALTER TABLE "PG_SPLIT_TRANSACTION" ADD "MOBILE_NUM" NUMBER(13,0);



CREATE TABLE "PG_ACCOUNT_HISTORY" 
   (    "ID" NUMBER(10,0), 
    "ENTITY_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
    "ENTITY_TYPE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
    "ACCOUNT_DESC" VARCHAR2(100 BYTE), 
    "CATEGORY" VARCHAR2(100 BYTE), 
    "CURRENT_BALANCE" NUMBER(20,0) DEFAULT 0, 
    "AVAILABLE_BALANCE" NUMBER(20,0) DEFAULT 0, 
    "CURRENCY" VARCHAR2(20 BYTE) DEFAULT 'USD', 
    "AUTO_PAYMENT_LIMIT" NUMBER(20,0), 
    "AUTO_PAYMENT_METHOD" VARCHAR2(20 BYTE), 
    "AUTO_TRANSFER_DAY" NUMBER(2,0), 
    "STATUS" VARCHAR2(20 BYTE), 
    "UPDATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
    "ACCOUNT_NUM" NUMBER(20,0), 
    "FEE_BALANCE" NUMBER(20,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "PG_TRANSACTION" add "CARD_HOLDER_NAME" VARCHAR2(50 BYTE);

CREATE SEQUENCE  "SEQ_PG_ACCOUNT_HISTORY"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 47 NOCACHE  NOORDER  NOCYCLE ;
ALTER TABLE "PG_ACCOUNT_HISTORY" ADD "PAYMENT_METHOD" VARCHAR2(20 BYTE);
ALTER TABLE "PG_ACCOUNT_HISTORY" ADD "TRANSACTION_ID" NUMBER(12,0);

CREATE SEQUENCE  "SEQ_PG_MERCHANT_USER_ADDRESS"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
CREATE TABLE "PG_MERCHANT_USER_ADDRESS"
  (
    "ID"               NUMBER(15,0) NOT NULL ENABLE,
    "ADDRESS1"         VARCHAR2(60 BYTE),
    "ADDRESS2"         VARCHAR2(60 BYTE),
    "CITY"             VARCHAR2(60 BYTE),
    "STATE"            VARCHAR2(60 BYTE),
    "COUNTRY"          VARCHAR2(60 BYTE),
    "PIN"              NUMBER(10,0),
    "MERCHANT_CODE"    VARCHAR2(50 BYTE),
    "MERCHANT_USER_ID" NUMBER(15,0) UNIQUE
  );
--26/06/2015 ADDED FOR TERMS AND CONDITIONS FOR RECURRING.
ALTER TABLE "PG_RECURRING_CUSTOMER_INFO" ADD(TERMS_FLAG VARCHAR2(4),TERMS_VERSION VARCHAR2(10));

--29/06/2015 ADDED PARENT MERCHANT ID FOR SUM MERCHANT CREATION
ALTER TABLE "PG_MERCHANT" ADD PARENT_MERCHANT_ID NUMBER(15,0); 
ALTER TABLE "PG_ACCOUNT" MODIFY "ID" NUMBER(10,0) PRIMARY KEY;  

--09/07/2015 MODIFIED ZIP CODE TO ALLOW ALPHA NUMERIC ACROSS THE BOARD
ALTER TABLE "PG_MERCHANT_USER_ADDRESS" MODIFY "PIN"  VARCHAR2(10 BYTE);
ALTER TABLE "PG_MERCHANT" MODIFY "PIN"  VARCHAR2(10 BYTE);


-- SANDBOX Release on 18/08/2015
--08/08/2015 ADDED FEE CODE FOR PARTNER 
-----------------------------------------------------
--  DDL for Sequence SEQ_PG_PARTNER_FEE_CODE
--------------------------------------------------------
CREATE SEQUENCE SEQ_PG_PARTNER_FEE_CODE MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 10 NOCACHE NOORDER NOCYCLE ;
  --------------------------------------------------------
  --  DDL for Table PG_PARTNER_FEE_CODE
  --------------------------------------------------------
    CREATE TABLE PG_PARTNER_FEE_CODE
    (
      PARTNER_FEE_CODE_ID NUMBER(20,0) NOT NULL ENABLE,
      PARTNER_NAME        VARCHAR2(50),
      PARTNER_ENTITY_ID   VARCHAR2(50 BYTE) NOT NULL ENABLE,
      PARTNER_ENTITY_TYPE VARCHAR2(50 BYTE),
      FEE_PERCENTAGE_ONLY DECIMAL(20,0),
      FLAT_FEE            NUMBER(20,0),
      CREATED_BY          VARCHAR2(20) NOT NULL,
      UPDATED_BY          VARCHAR2(20),
      CREATED_DATE        TIMESTAMP (6) NOT NULL,
      UPDATED_DATE        TIMESTAMP (6),
      ACCOUNT_NUM          NUMBER(20,0)
    );
  ALTER TABLE PG_PARTNER_FEE_CODE ADD CONSTRAINT PG_PARTNER_FEE_CODE_PK PRIMARY KEY (PARTNER_FEE_CODE_ID);
  ALTER TABLE PG_PARTNER_FEE_CODE ADD CONSTRAINT PARTNER_ENTITY_ID_UK UNIQUE (PARTNER_ENTITY_ID);
  ALTER TABLE PG_PARTNER_FEE_CODE ADD CONSTRAINT ACCOUNT_NUM_UK UNIQUE (ACCOUNT_NUM);
  -----------------------------------------------------
--  DDL for Sequence SEQ_PG_PARTNER_FEE_CODE
--------------------------------------------------------

  CREATE SEQUENCE SEQ_PG_ACQUIRER_FEE_CODE MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 10 NOCACHE NOORDER NOCYCLE ;
  --------------------------------------------------------
  --  DDL for Table PG_ACQUIRER_FEE_CODE
  --------------------------------------------------------
    CREATE TABLE PG_ACQUIRER_FEE_CODE
    (
      ACQUIRER_FEE_CODE_ID NUMBER(20,0) NOT NULL ENABLE,
      ACQUIRER_NAME        VARCHAR2(50),
      PARTNER_ID   NUMBER(20,0) NOT NULL ENABLE,
      FEE_PERCENTAGE_ONLY  DECIMAL(20,0),
      FLAT_FEE             NUMBER(20,0),
      UPDATED_BY           VARCHAR2(20),
      UPDATED_DATE         TIMESTAMP (6)
     
    );
  ALTER TABLE PG_ACQUIRER_FEE_CODE ADD CONSTRAINT PG_ACQUIRER_FEE_CODE_PK PRIMARY KEY (ACQUIRER_FEE_CODE_ID);
  ALTER TABLE PG_ACQUIRER_FEE_CODE ADD MERCHANT_CODE VARCHAR2(50);
  ALTER TABLE PG_ACQUIRER_FEE_CODE ADD CONSTRAINT ACQUIRER_NAME_AND_PARTNER_UK UNIQUE (ACQUIRER_NAME,PARTNER_ID,MERCHANT_CODE);
  
    --------------------------------------------------------
  -- 14/08/2015 SEQUENCE FOR  SEQ_PG_TRANSFERS 
  --------------------------------------------------------
    
    CREATE SEQUENCE "SEQ_PG_TRANSFERS"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
       --------------------------------------------------------
  -- 14/08/2015 DDL  for Table PG_TRANSFERS 
  --------------------------------------------------------
CREATE TABLE "PG_TRANSFERS"
    (
      "PG_TRANSFERS_ID"                    NUMBER(10,0) PRIMARY KEY ,
      "AMOUNT"          NUMBER(20,0),
      "MERCHANT_ID"           NUMBER(15,0),
	  "FROM_ACCOUNT"   VARCHAR2(20 BYTE),
	  "TO_ACCOUNT"   VARCHAR2(20 BYTE),
	  "NAME_ON_ACCOUNT"   VARCHAR2(50 BYTE),
	  "CITY"   VARCHAR2(20 BYTE),
	  "STATE"   VARCHAR2(20 BYTE),
	  "ACCOUNT_TYPE"   VARCHAR2(20 BYTE),
	  "BANK_ROUTING_NUMBER"   VARCHAR2(20 BYTE),
	  "TRANSFER_MODE"         VARCHAR2(20 BYTE),
      "CREATED_DATE"          TIMESTAMP (6),
      "UPDATED_DATE"          TIMESTAMP (6),
      "STATUS"                NUMBER(1,0),
      "TXN_DESCRIPTION"       VARCHAR2(500 BYTE)
      
    );
    ALTER TABLE PG_TRANSFERS MODIFY STATUS VARCHAR2(20 BYTE);
        --------------------------------------------------------
  -- 14/08/2015 SEQUENCE FOR  SEQ_PG_LEGAL_ENTITY 
  --------------------------------------------------------
    CREATE SEQUENCE "SEQ_PG_LEGAL_ENTITY" MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 10 NOCACHE NOORDER NOCYCLE ;
            --------------------------------------------------------
  -- 14/08/2015 DDL FOR  PG_LEGAL_ENTITY 
  --------------------------------------------------------
 CREATE TABLE "PG_LEGAL_ENTITY"
  (
    "PG_LEGAL_ENTITY_ID"     NUMBER(10,0) PRIMARY KEY ,
    "LEGAL_ENTITY_NAME"      VARCHAR2(500 BYTE),
    "LEGAL_ENTITY_TYPE"      VARCHAR2(500 BYTE),
    "TAX_ID"                 VARCHAR2(500 BYTE),
    "MERCHANT_ID"            NUMBER(15,0),
    "FIRST_NAME"             VARCHAR2(500 BYTE),
    "LAST_NAME"              VARCHAR2(500 BYTE),
    "DATE_OF_BIRTH"          VARCHAR2(10 BYTE),
    "SSN"                    VARCHAR2(500 BYTE),
    "COUNTRY_OF_RESIDENCE"   VARCHAR2(20 BYTE),
    "COUNTRY_OF_CITIZENSHIP" VARCHAR2(20 BYTE),
    "HOME_PHONE"             VARCHAR2(20 BYTE),
    "MOBILE_PHONE"           VARCHAR2(20 BYTE),
    "ADDRESS1"               VARCHAR2(60 BYTE),
    "ADDRESS2"               VARCHAR2(60 BYTE),
    "CITY"                   VARCHAR2(60 BYTE),
    "STATE"                  VARCHAR2(60 BYTE),
    "COUNTRY"                VARCHAR2(60 BYTE),
    "PIN"                    NUMBER(10,0),
    "PASSPORT_NUMBER"        VARCHAR2(20 BYTE),
    "CREATED_DATE"           TIMESTAMP (6),
    "UPDATED_DATE"           TIMESTAMP (6),
    "ANNUAL_CARD_SALE"       NUMBER(5,0)
  );
  --------------------------------------------------------
  -- 14/08/2015 ALTER SCRIPT FOR  PG_MERCHANT_BANK 
  --------------------------------------------------------
   ALTER TABLE PG_MERCHANT_BANK ADD NAME_ON_ACCOUNT VARCHAR2(50 BYTE);
   
   ALTER TABLE PG_ACQUIRER_FEE_CODE MODIFY  FEE_PERCENTAGE_ONLY  DECIMAL(20,2);
   --21-08-2015 CHANGES FOR AUTOPAYMET 
   ALTER TABLE PG_ACCOUNT MODIFY  AUTO_TRANSFER_DAY  VARCHAR2(80 BYTE);
   ALTER TABLE PG_ACCOUNT_HISTORY MODIFY  AUTO_TRANSFER_DAY  VARCHAR2(80 BYTE);

commit;