--------------------------------------------------------
--  File created - Monday-January-05-2015   
--------------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE PG_FEATURES
--   FILTER = none used
---------------------------------------------------
REM INSERTING into PG_FEATURES
Insert into PG_FEATURES (FEATURE_ID,FEATURE_NAME,FEATURE_URL) values (1,'Merchant Management','merchantManagement');
Insert into PG_FEATURES (FEATURE_ID,FEATURE_NAME,FEATURE_URL) values (2,'User Management','userManagement');
Insert into PG_FEATURES (FEATURE_ID,FEATURE_NAME,FEATURE_URL) values (3,'Transaction Management','transactionManagement');
Insert into PG_FEATURES (FEATURE_ID,FEATURE_NAME,FEATURE_URL) values (4,'Settlement Report','settlementReport');

---------------------------------------------------
--   END DATA FOR TABLE PG_FEATURES
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE PG_SWITCH_TRANSACTION
--   FILTER = none used
---------------------------------------------------
REM INSERTING into PG_SWITCH_TRANSACTION

---------------------------------------------------
--   END DATA FOR TABLE PG_SWITCH_TRANSACTION
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE PG_SUB_FEATURES
--   FILTER = none used
---------------------------------------------------
REM INSERTING into PG_SUB_FEATURES
Insert into PG_SUB_FEATURES (SUB_FEATURE_ID,FEATURE_ID,FEATURE_NAME,FEATURE_URL) values (1,1,'Store Management','storeManagement');
Insert into PG_SUB_FEATURES (SUB_FEATURE_ID,FEATURE_ID,FEATURE_NAME,FEATURE_URL) values (2,1,'Terminal Merchant','terminalmanagement');
Insert into PG_SUB_FEATURES (SUB_FEATURE_ID,FEATURE_ID,FEATURE_NAME,FEATURE_URL) values (3,3,'Transaction Report','transactionReport');
Insert into PG_SUB_FEATURES (SUB_FEATURE_ID,FEATURE_ID,FEATURE_NAME,FEATURE_URL) values (4,3,'Transaction Summary','transactionSummary');

---------------------------------------------------
--   END DATA FOR TABLE PG_SUB_FEATURES
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE PG_ACTIVITY_LOG
--   FILTER = none used
---------------------------------------------------
REM INSERTING into PG_ACTIVITY_LOG

---------------------------------------------------
--   END DATA FOR TABLE PG_ACTIVITY_LOG
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE PG_USER_ROLES
--   FILTER = none used
---------------------------------------------------
REM INSERTING into PG_USER_ROLES
Insert into PG_USER_ROLES (ROLE_ID,ROLE_NAME) values (1,'SuperAdmin');
Insert into PG_USER_ROLES (ROLE_ID,ROLE_NAME) values (2,'MerchantAdmin');
Insert into PG_USER_ROLES (ROLE_ID,ROLE_NAME) values (3,'StoreAdmin');
Insert into PG_USER_ROLES (ROLE_ID,ROLE_NAME) values (4,'PortalUser');

---------------------------------------------------
--   END DATA FOR TABLE PG_USER_ROLES
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE PG_MERCHANT_BANK
--   FILTER = none used
---------------------------------------------------
REM INSERTING into PG_MERCHANT_BANK

---------------------------------------------------
--   END DATA FOR TABLE PG_MERCHANT_BANK
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE PG_MERCHANT
--   FILTER = none used
---------------------------------------------------
REM INSERTING into PG_MERCHANT
Insert into PG_MERCHANT (MERCHANT_CODE,BUSINESS_NAME,PHONE,TIN,SSN,PIN,ADDRESS1,ADDRESS2,CITY,STATE,COUNTRY,CREATED_DATE,UPDATED_DATE,VALID_FROM_DATE,VALID_TO_DATE,STATUS,ID,MCC,DAILY_TXN_LIMIT,ALLOW_INTERNATIONAL_TXN,MERCHANT_TYPE) values (222222222222222,'Virtual Merchant1',9999999999,'TIN000000001',null,null,'virtual Address',null,null,null,null,to_timestamp('02-JAN-15 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('02-JAN-15 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('02-JAN-15 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('02-JAN-15 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),0,1,'TEST',10000,1,'TEST');
Insert into PG_MERCHANT (MERCHANT_CODE,BUSINESS_NAME,PHONE,TIN,SSN,PIN,ADDRESS1,ADDRESS2,CITY,STATE,COUNTRY,CREATED_DATE,UPDATED_DATE,VALID_FROM_DATE,VALID_TO_DATE,STATUS,ID,MCC,DAILY_TXN_LIMIT,ALLOW_INTERNATIONAL_TXN,MERCHANT_TYPE) values (471382812818315,'POS merchant',9999999999,'TIN000000001',null,null,'Virtual Address',null,null,null,null,to_timestamp('02-JAN-15 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('02-JAN-15 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('02-JAN-15 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('02-JAN-15 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),0,2,'TEST',10000,1,'TEST');

---------------------------------------------------
--   END DATA FOR TABLE PG_MERCHANT
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE PG_ROLE_FEATURE_MAPPING
--   FILTER = none used
---------------------------------------------------
REM INSERTING into PG_ROLE_FEATURE_MAPPING
Insert into PG_ROLE_FEATURE_MAPPING (ID,ROLE_ID,FEATURE_ID,DISPLAY_ORDER) values (1,1,1,1);
Insert into PG_ROLE_FEATURE_MAPPING (ID,ROLE_ID,FEATURE_ID,DISPLAY_ORDER) values (2,1,2,2);
Insert into PG_ROLE_FEATURE_MAPPING (ID,ROLE_ID,FEATURE_ID,DISPLAY_ORDER) values (3,1,3,3);
Insert into PG_ROLE_FEATURE_MAPPING (ID,ROLE_ID,FEATURE_ID,DISPLAY_ORDER) values (4,1,4,4);
Insert into PG_ROLE_FEATURE_MAPPING (ID,ROLE_ID,FEATURE_ID,DISPLAY_ORDER) values (5,2,1,1);
Insert into PG_ROLE_FEATURE_MAPPING (ID,ROLE_ID,FEATURE_ID,DISPLAY_ORDER) values (6,2,2,2);
Insert into PG_ROLE_FEATURE_MAPPING (ID,ROLE_ID,FEATURE_ID,DISPLAY_ORDER) values (7,2,3,3);
Insert into PG_ROLE_FEATURE_MAPPING (ID,ROLE_ID,FEATURE_ID,DISPLAY_ORDER) values (8,2,4,4);

---------------------------------------------------
--   END DATA FOR TABLE PG_ROLE_FEATURE_MAPPING
---------------------------------------------------

---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE PG_FEE_DETAIL
--   FILTER = none used
---------------------------------------------------
REM INSERTING into PG_FEE_DETAIL
Insert into PG_FEE_DETAIL (ID,TXN_TYPE,FEE_AMOUNT,CREATED_DATE,STATUS) values (1,'auth',0,to_timestamp('02-JAN-15 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),0);
Insert into PG_FEE_DETAIL (ID,TXN_TYPE,FEE_AMOUNT,CREATED_DATE,STATUS) values (2,'sale',0,to_timestamp('02-JAN-15 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),0);
Insert into PG_FEE_DETAIL (ID,TXN_TYPE,FEE_AMOUNT,CREATED_DATE,STATUS) values (3,'sale-adj',0,to_timestamp('02-JAN-15 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),0);
Insert into PG_FEE_DETAIL (ID,TXN_TYPE,FEE_AMOUNT,CREATED_DATE,STATUS) values (4,'void',0,to_timestamp('02-JAN-15 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),0);
Insert into PG_FEE_DETAIL (ID,TXN_TYPE,FEE_AMOUNT,CREATED_DATE,STATUS) values (5,'reversal',0,to_timestamp('02-JAN-15 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),0);

---------------------------------------------------
--   END DATA FOR TABLE PG_FEE_DETAIL
---------------------------------------------------

---------------------------------------------------
--   END DATA FOR TABLE PG_SERVICE_ADMIN_USER
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE PG_SWITCH
--   FILTER = none used
---------------------------------------------------
REM INSERTING into PG_SWITCH
Insert into PG_SWITCH (ID,SWITCH_NAME,SWITCH_TYPE,SWITCH_IP,SWITCH_PORT,STATUS,PRIORITY,"CREATED_BY",UPDATED_BY) values (1,'Chatak','SOCKET','192.168.1.215','22403',1,1,1,1);

---------------------------------------------------
--   END DATA FOR TABLE PG_SWITCH
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE PG_EMV_TRANSACTION
--   FILTER = none used
---------------------------------------------------
REM INSERTING into PG_EMV_TRANSACTION

---------------------------------------------------
--   END DATA FOR TABLE PG_EMV_TRANSACTION
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE PG_TRANSACTION
--   FILTER = none used
---------------------------------------------------
REM INSERTING into PG_TRANSACTION

---------------------------------------------------
--   END DATA FOR TABLE PG_TRANSACTION
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE PG_MERCHANT_SETTINGS
--   FILTER = none used
---------------------------------------------------
REM INSERTING into PG_MERCHANT_SETTINGS

---------------------------------------------------
--   END DATA FOR TABLE PG_MERCHANT_SETTINGS
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE PG_BLACKLISTED_CARD
--   FILTER = none used
---------------------------------------------------
REM INSERTING into PG_BLACKLISTED_CARD
Insert into PG_BLACKLISTED_CARD (ID,CARD_NUM,CREATED_DATE,STATUS) values (1,'1111111111111111',to_timestamp('02-JAN-15 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),0);

---------------------------------------------------
--   END DATA FOR TABLE PG_BLACKLISTED_CARD
---------------------------------------------------

---------------------------------------------------
-- Data for OAuth client
---------------------------------------------------
INSERT
INTO PG_APPLICATION_CLIENT
  (
    ID,
    APP_NAME,
    APP_DESCRIPTION,
    APP_ADMIN_EMAIL,
    APP_CLIENT_NAME,
    APP_CLIENT_EMAIL,
    APP_CLIENT_PHONE,
    APP_CLIENT_ADDRESS,
    APP_CLIENT_CITY,
    APP_CLIENT_COUNTRY,
    APP_CLIENT_ZIP,
    APP_CLIENT_ROLE,
    STATUS,
    ACTIVE_FROM,
    ACTIVE_TILL,
    APP_CLIENT_ID,
    APP_CLIENT_ACCESS,
    APP_AUTH_USER,
    APP_AUTH_PASS,
    CREATED_BY,
    UPDATED_BY,
    CREATED_DATE,
    UPDATED_DATE
  )
  VALUES
  (
    '2',
    'Token server',
    'Online Checkout',
    'raj.k@girmiti.com',
    'Token server auth',
    'raj.k@girmiti.com',
    '+919632506005',
    'Bangalore',
    'Bangalore',
    'IND',
    '560037',
    'ROLE_APP',
    '0',
    TO_TIMESTAMP('01-02-15 01:00:00 AM', 'DD-MM-RR HH12:MI:SSXFF AM'),
    TO_TIMESTAMP('01-02-16 11:00:00 PM', 'DD-MM-RR HH12:MI:SSXFF AM'),
    'resgpcqlmg8lydip',
    '9570AFBEMA36EM4130M9B72M44C9D3C9703C',
    'izf8p5t73ffcshzq1lpa2adho0tgm6zt',
    'C7511182M9FEFM4D5DM84A5M68B1188F6220',
    '1',
    '1',
    SYSDATE,
    SYSDATE
  );

------------------------------------------------------
-- TMS master data script
------------------------------------------------------
 INSERT INTO PG_PAN_LENGTH (PAN_LENGTH_ID, PAN_LENGTH, CREATED_BY, CREATED_DATE) VALUES ('1', '12', 'SEED DATA', sysdate);
 INSERT INTO PG_PAN_LENGTH (PAN_LENGTH_ID, PAN_LENGTH, CREATED_BY, CREATED_DATE) VALUES ('2', '13', 'SEED DATA', sysdate);
 INSERT INTO PG_PAN_LENGTH (PAN_LENGTH_ID, PAN_LENGTH, CREATED_BY, CREATED_DATE) VALUES ('3', '14', 'SEED DATA', sysdate);
 INSERT INTO PG_PAN_LENGTH (PAN_LENGTH_ID, PAN_LENGTH, CREATED_BY, CREATED_DATE) VALUES ('4', '15', 'SEED DATA', sysdate);
 INSERT INTO PG_PAN_LENGTH (PAN_LENGTH_ID, PAN_LENGTH, CREATED_BY, CREATED_DATE) VALUES ('5', '16', 'SEED DATA', sysdate);
 INSERT INTO PG_PAN_LENGTH (PAN_LENGTH_ID, PAN_LENGTH, CREATED_BY, CREATED_DATE) VALUES ('6', '17', 'SEED DATA', sysdate);
 INSERT INTO PG_PAN_LENGTH (PAN_LENGTH_ID, PAN_LENGTH, CREATED_BY, CREATED_DATE) VALUES ('7', '18', 'SEED DATA', sysdate);
 INSERT INTO PG_PAN_LENGTH (PAN_LENGTH_ID, PAN_LENGTH, CREATED_BY, CREATED_DATE) VALUES ('8', '19', 'SEED DATA', sysdate);
 INSERT INTO PG_PAN_LENGTH (PAN_LENGTH_ID, PAN_LENGTH, CREATED_BY, CREATED_DATE) VALUES ('9', '20', 'SEED DATA', sysdate);
 
INSERT INTO PG_ACTION_CODE_PARAMETERS (ACTION_CODE_ID, ACTION_CODE_NAME, CREATED_BY, CREATED_DATE) VALUES ('1', 'Visa action Codes', 'SEED DATA', sysdate);
INSERT INTO PG_ACTION_CODE_PARAMETERS (ACTION_CODE_ID, ACTION_CODE_NAME, CREATED_BY, CREATED_DATE) VALUES ('2', 'Master action codes', 'SEED DATA',sysdate);
INSERT INTO PG_ACTION_CODE_PARAMETERS (ACTION_CODE_ID, ACTION_CODE_NAME, CREATED_BY, CREATED_DATE) VALUES ('3', 'Amex action codes', 'SEED DATA', sysdate);
INSERT INTO PG_ACTION_CODE_PARAMETERS (ACTION_CODE_ID, ACTION_CODE_NAME, CREATED_BY, CREATED_DATE) VALUES ('4', 'Discover action codes', 'SEED DATA', sysdate);
INSERT INTO PG_ACTION_CODE_PARAMETERS (ACTION_CODE_ID, ACTION_CODE_NAME, CREATED_BY, CREATED_DATE) VALUES ('5', 'Maestro action codes', 'SEED DATA', sysdate);


INSERT INTO PG_CA_PUBLIC_KEYS (PUBLIC_KEY_ID, PUBLIC_KEY_NAME, CREATED_BY, CREATED_DATE) VALUES ('1', 'Visa 1182 bit public key',
 'SEED DATA', sysdate);
 INSERT INTO PG_CA_PUBLIC_KEYS (PUBLIC_KEY_ID, PUBLIC_KEY_NAME, CREATED_BY, CREATED_DATE) VALUES ('2', 'Visa 1912 bit public key', 'SEED DATA', sysdate);
 INSERT INTO PG_CA_PUBLIC_KEYS (PUBLIC_KEY_ID, PUBLIC_KEY_NAME, CREATED_BY, CREATED_DATE) VALUES ('3', 'Master card 1182 bit public key', 'SEED DATA', sysdate);
 INSERT INTO PG_CA_PUBLIC_KEYS (PUBLIC_KEY_ID, PUBLIC_KEY_NAME, CREATED_BY, CREATED_DATE) VALUES ('4', 'Master card 1912 bit public key', 'SEED DATA', sysdate);
 INSERT INTO PG_CA_PUBLIC_KEYS (PUBLIC_KEY_ID, PUBLIC_KEY_NAME, CREATED_BY, CREATED_DATE) VALUES ('5', 'Maestro 1182 bit public key', 'SEED DATA', sysdate);
 INSERT INTO PG_CA_PUBLIC_KEYS (PUBLIC_KEY_ID, PUBLIC_KEY_NAME, CREATED_BY, CREATED_DATE) VALUES ('6', 'Maestro 1912 bit public key', 'SEED DATA', sysdate);
 
 INSERT INTO PG_AID (APPLICATION_ID, APPLICATION_NAME, CREATED_BY, CREATED_DATE) VALUES ('1', 'VSDC Application', 'SEED DATA', sysdate);
 INSERT INTO PG_AID (APPLICATION_ID, APPLICATION_NAME, CREATED_BY, CREATED_DATE) VALUES ('2', 'Mchip Application', 'SEED DATA', sysdate);
 INSERT INTO PG_AID (APPLICATION_ID, APPLICATION_NAME, CREATED_BY, CREATED_DATE) VALUES ('3', 'Maestro Application', 'SEED DATA', sysdate);
 INSERT INTO PG_AID (APPLICATION_ID, APPLICATION_NAME, CREATED_BY, CREATED_DATE) VALUES ('4', 'Amex Application', 'SEED DATA', sysdate);
 INSERT INTO PG_AID (APPLICATION_ID, APPLICATION_NAME, CREATED_BY, CREATED_DATE) VALUES ('5', 'Discover Application', 'SEED DATA', sysdate);
 INSERT INTO PG_AID (APPLICATION_ID, APPLICATION_NAME, CREATED_BY, CREATED_DATE) VALUES ('6', 'Master Application', 'SEED DATA', sysdate);
 INSERT INTO PG_AID (APPLICATION_ID, APPLICATION_NAME, CREATED_BY, CREATED_DATE) VALUES ('7', 'VISA Application', 'SEED DATA', sysdate);
 
 
 INSERT INTO PG_CURRENCY_CODE (ID, COUNTRY_ID, CODE, CREATED_BY, CREATED_DATE) VALUES ('1', '1', 'INR', 'SEED DATA', sysdate);
 INSERT INTO PG_CURRENCY_CODE (ID, COUNTRY_ID, CODE, CREATED_BY, CREATED_DATE) VALUES ('2', '1', 'USD', 'SEED DATA', sysdate);
 
 INSERT INTO PG_LOCAL_CURRENCY_CODE (ID, COUNTRY_ID, CODE, CREATED_BY, CREATED_DATE) VALUES ('1', '1', 'INR', 'SEED DATA', sysdate);
 
 
 INSERT INTO PG_ISO_COUNTRY_CODE (ID, CODE, NAME, CREATED_BY, CREATED_DATE) VALUES ('1', '356', 'IND', 'SEED DATA', sysdate);
 INSERT INTO PG_ISO_COUNTRY_CODE (ID, CODE, NAME, CREATED_BY, CREATED_DATE) VALUES ('2', '840', 'USA', 'SEED DATA', sysdate);
 
 INSERT INTO PG_COUNTRY(ID, NAME) VALUES (1,'India');
 
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (1, 'Bihar', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (2, 'Orissa', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (3, 'Jharkhand', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (4, 'West Bengal', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (5, 'Rajasthan', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (6, 'Gujarat', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (7, 'Goa', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (8, 'Maharashtra', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (9, 'Andhra Pradesh', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (10, 'Karnataka', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (11, 'Tamilnadu', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (12, 'Kerala', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (13, 'Madhya Pradesh', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (14, 'Chhattisgarh', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (15, 'Assam', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (16, 'Sikkim', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (17, 'Nagaland', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (18, 'Meghalaya', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (19, 'Manipur', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (20, 'Mizoram', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (21, 'Tripura', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (22, 'Arunachal Pradesh', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (23, 'Jammu and Kashmir', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (24, 'Himachal Pradesh', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (25, 'Punjab', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (26, 'Uttarakhand', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (27, 'Haryana', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (28, 'Andaman and Nicobar', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (29, 'Chandigarh', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (30, 'Dadra and Nagar Haveli', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (31, 'Daman and Diu', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (32, 'Lakshadeep', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (33, 'Delhi', 'Active', 1);
INSERT INTO PG_STATE(ID, NAME, STATUS, COUNTRY_ID) VALUES (34, 'Puducherry', 'Active', 1);


INSERT INTO PG_ADMIN_USER (ADMIN_USER_ID, ADDRESS1, ADDRESS2, CITY, COUNTRY, CREATED_BY, CREATED_DATE, EMAIL, EMAIL_VERIFIED, FIRST_NAME, LANGUAGE, LAST_LOGIN, LAST_LOGIN_IP, LAST_NAME, PASS_RETRY_COUNT, PASSWORD, PHONE, STATE, STATUS, USER_NAME, USER_ROLE_ID, ZIP, USER_TYPE, SECURITY_QUESTION, SECURITY_ANSWER)  VALUES ('1', 'Bangalore', 'Bangalore', 'Bangalore', 'India', 'SEED DATA', sysdate, 'tms1@mail.com', '1', 'System', 'English', sysdate, '', 'System', '0', '1900F86A319CB3C2AE1E66B8D50290A4', '1234567892', 'Karnataka', 0, 'skipper1', '1', '560037','TMSA','what is your name','_crypt_mw_MgKi8rAm3iBtNiM19A02N20V11I==');

INSERT INTO PG_ADMIN_USER (ADMIN_USER_ID, ADDRESS1, ADDRESS2, CITY, COUNTRY, CREATED_BY, CREATED_DATE, EMAIL, EMAIL_VERIFIED, FIRST_NAME, LANGUAGE, LAST_LOGIN, LAST_LOGIN_IP, LAST_NAME, PASS_RETRY_COUNT, PASSWORD, PHONE, STATE, STATUS, USER_NAME, USER_ROLE_ID, ZIP, USER_TYPE, SECURITY_QUESTION, SECURITY_ANSWER) VALUES ('2', 'Bangalore', 'Bangalore', 'Bangalore', 'India', 'SEED DATA', sysdate, 'tms2@mail.com', '1', 'System', 'English', sysdate, '', 'System', '0', '1900F86A319CB3C2AE1E66B8D50290A4', '1234567892', 'Karnataka', 0, 'skipper2', '1', '560037','TMSA','what is your name','_crypt_mw_MgKi8rAm3iBtNiM19A02N20V11I==');

INSERT INTO PG_ADMIN_USER (ADMIN_USER_ID, ADDRESS1, ADDRESS2, CITY, COUNTRY, CREATED_BY, CREATED_DATE, EMAIL, EMAIL_VERIFIED, FIRST_NAME, LANGUAGE, LAST_LOGIN, LAST_LOGIN_IP, LAST_NAME, PASS_RETRY_COUNT, PASSWORD, PHONE, STATE, STATUS, USER_NAME, USER_ROLE_ID, ZIP, USER_TYPE, SECURITY_QUESTION, SECURITY_ANSWER) VALUES ('3', 'Bangalore', 'Bangalore', 'Bangalore', 'India', 'SEED DATA', sysdate, 'tms3@mail.com', '1', 'System', 'English', sysdate, '', 'System', '0', '1900F86A319CB3C2AE1E66B8D50290A4', '1234567892', 'Karnataka', 0, 'skipper3', '1', '560037','TMSA','what is your name','_crypt_mw_MgKi8rAm3iBtNiM19A02N20V11I==');

INSERT INTO PG_ADMIN_USER (ADMIN_USER_ID, ADDRESS1, ADDRESS2, CITY, COUNTRY, CREATED_BY, CREATED_DATE, EMAIL, EMAIL_VERIFIED, FIRST_NAME, LANGUAGE, LAST_LOGIN, LAST_LOGIN_IP, LAST_NAME, PASS_RETRY_COUNT, PASSWORD, PHONE, STATE, STATUS, USER_NAME, USER_ROLE_ID, ZIP, USER_TYPE, SECURITY_QUESTION, SECURITY_ANSWER) VALUES ('4', 'Bangalore', 'Bangalore', 'Bangalore', 'India', 'SEED DATA', sysdate, 'tms4@mail.com', '1', 'System', 'English', sysdate, '', 'System', '0', '1900F86A319CB3C2AE1E66B8D50290A4', '1234567892', 'Karnataka', 0, 'skipper4', '1', '560037','TMSA','what is your name','_crypt_mw_MgKi8rAm3iBtNiM19A02N20V11I==');

INSERT INTO PG_ADMIN_USER (ADMIN_USER_ID, ADDRESS1, ADDRESS2, CITY, COUNTRY, CREATED_BY, CREATED_DATE, EMAIL, EMAIL_VERIFIED, FIRST_NAME, LANGUAGE, LAST_LOGIN, LAST_LOGIN_IP, LAST_NAME, PASS_RETRY_COUNT, PASSWORD, PHONE, STATE, STATUS, USER_NAME, USER_ROLE_ID, ZIP, USER_TYPE, SECURITY_QUESTION, SECURITY_ANSWER) VALUES ('5', 'Bangalore', 'Bangalore', 'Bangalore', 'India', 'SEED DATA', sysdate, 'acqadmin@chatak.com', '1', 'System', 'English', sysdate, '', 'System', '0', '5F37EF747797C8D64A41BE8BAF5519D2', '1234567892', 'Karnataka', 0, 'skipper4', '1', '560037','TMSA','what is your name','_crypt_mw_MgKi8rAm3iBtNiM19A02N20V11I==');

INSERT INTO PG_ADMIN_USER (ADMIN_USER_ID, ADDRESS1, ADDRESS2, CITY, COUNTRY, CREATED_BY, CREATED_DATE, EMAIL, EMAIL_VERIFIED, FIRST_NAME, LANGUAGE, LAST_LOGIN, LAST_LOGIN_IP, LAST_NAME, PASS_RETRY_COUNT, PASSWORD, PHONE, STATE, STATUS, USER_NAME, USER_ROLE_ID, ZIP, USER_TYPE, SECURITY_QUESTION, SECURITY_ANSWER) VALUES ('6', 'Bangalore', 'Bangalore', 'Bangalore', 'India', 'SEED DATA', sysdate, 'acqpg@chatak.com', '1', 'System', 'English', sysdate, '', 'System', '0', '5F37EF747797C8D64A41BE8BAF5519D2', '1234567892', 'Karnataka', 0, 'skipper4', '1', '560037','TMSA','what is your name','_crypt_mw_MgKi8rAm3iBtNiM19A02N20V11I==');

INSERT INTO PG_MAGNETIC_STRIPE_PARAMETERS (MAGNETIC_STRIPE_ID, MAGNETIC_STRIPE_NAME, CREATED_BY, CREATED_DATE) VALUES ('1', 'VISA BIN Range', 'SEED DATA', sysdate);
 INSERT INTO PG_MAGNETIC_STRIPE_PARAMETERS (MAGNETIC_STRIPE_ID, MAGNETIC_STRIPE_NAME, CREATED_BY, CREATED_DATE) VALUES ('2', 'Master BIN Range', 'SEED DATA', sysdate);
 INSERT INTO PG_MAGNETIC_STRIPE_PARAMETERS (MAGNETIC_STRIPE_ID, MAGNETIC_STRIPE_NAME, CREATED_BY, CREATED_DATE) VALUES ('3', 'Amex Bin Range', 'SEED DATA', sysdate);
 INSERT INTO PG_MAGNETIC_STRIPE_PARAMETERS (MAGNETIC_STRIPE_ID, MAGNETIC_STRIPE_NAME, CREATED_BY, CREATED_DATE) VALUES ('4', 'Maestro BIN Range', 'SEED DATA', sysdate);
 INSERT INTO PG_MAGNETIC_STRIPE_PARAMETERS (MAGNETIC_STRIPE_ID, MAGNETIC_STRIPE_NAME, CREATED_BY, CREATED_DATE) VALUES ('5', 'Discover BIN Range', 'SEED DATA', sysdate);
 
  

INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_PURCHASE - APPROVED', '00', '00','APPROVED');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_PURCHASE - INSUFFICIENT_FUNDS', '00', '51','INSUFFICIENT_FUNDS');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_PURCHASE - EXCEEDS_WITHDRAW_FREQUENCY_LIMIT', '00', '65','EXCEEDS_WITHDRAW_FREQUENCY_LIMIT');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_PURCHASE - EXCEEDS_WITHDRAW_AMOUNT_LIMIT', '00', '61','EXCEEDS_WITHDRAW_AMOUNT_LIMIT');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_PURCHASE - CVV_FAILED', '00', '89','CVV_FAILED');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_PURCHASE - EXPIRED_CARD', '00', '54','EXPIRED_CARD');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_PURCHASE - INVALID_AMOUNT', '00', '13','INVALID_AMOUNT');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_PURCHASE - INCORRECT_PIN', '00', '55','INCORRECT_PIN');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_PURCHASE - BAD_CVV2', '00', 'SR','BAD_CVV2');

-- ATM withdraw transaction fee codes
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'ATM_WITHDRAW - APPROVED', '01', '00','APPROVED');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'ATM_WITHDRAW - INSUFFICIENT_FUNDS', '01', '51','INSUFFICIENT_FUNDS');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'ATM_WITHDRAW - EXCEEDS_WITHDRAW_FREQUENCY_LIMIT', '01', '65','EXCEEDS_WITHDRAW_FREQUENCY_LIMIT');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'ATM_WITHDRAW - EXCEEDS_WITHDRAW_AMOUNT_LIMIT', '01', '61','EXCEEDS_WITHDRAW_AMOUNT_LIMIT');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'ATM_WITHDRAW - CVV_FAILED', '01', '89','CVV_FAILED');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'ATM_WITHDRAW - EXPIRED_CARD', '01', '54','EXPIRED_CARD');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'ATM_WITHDRAW - INVALID_AMOUNT', '01', '13','INVALID_AMOUNT');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'ATM_WITHDRAW - INCORRECT_PIN', '01', '55','INCORRECT_PIN');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'ATM_WITHDRAW - BAD_CVV2', '01', 'SR','BAD_CVV2');

-- POS purchase with cash back transaction fee codes
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_PURCHASE_WITH_CASHBACK - APPROVED', '09', '00','APPROVED');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_PURCHASE_WITH_CASHBACK - INSUFFICIENT_FUNDS', '09', '51','INSUFFICIENT_FUNDS');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_PURCHASE_WITH_CASHBACK - EXCEEDS_WITHDRAW_FREQUENCY_LIMIT', '09', '65','EXCEEDS_WITHDRAW_FREQUENCY_LIMIT');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_PURCHASE_WITH_CASHBACK - EXCEEDS_WITHDRAW_AMOUNT_LIMIT', '09', '61','EXCEEDS_WITHDRAW_AMOUNT_LIMIT');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_PURCHASE_WITH_CASHBACK - CVV_FAILED', '09', '89','CVV_FAILED');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_PURCHASE_WITH_CASHBACK - EXPIRED_CARD', '09', '54','EXPIRED_CARD');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_PURCHASE_WITH_CASHBACK - INVALID_AMOUNT', '09', '13','INVALID_AMOUNT');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_PURCHASE_WITH_CASHBACK - INCORRECT_PIN', '09', '55','INCORRECT_PIN');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_PURCHASE_WITH_CASHBACK - BAD_CVV2', '09', 'SR','BAD_CVV2');

-- POS refund transaction fee codes
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_REFUND - APPROVED', '20', '00','APPROVED');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_REFUND - INSUFFICIENT_FUNDS', '20', '51','INSUFFICIENT_FUNDS');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_REFUND - EXCEEDS_WITHDRAW_FREQUENCY_LIMIT', '20', '65','EXCEEDS_WITHDRAW_FREQUENCY_LIMIT');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_REFUND - EXCEEDS_WITHDRAW_AMOUNT_LIMIT', '20', '61','EXCEEDS_WITHDRAW_AMOUNT_LIMIT');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_REFUND - CVV_FAILED', '20', '89','CVV_FAILED');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_REFUND - EXPIRED_CARD', '20', '54','EXPIRED_CARD');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_REFUND - INVALID_AMOUNT', '20', '13','INVALID_AMOUNT');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_REFUND - INCORRECT_PIN', '20', '55','INCORRECT_PIN');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_REFUND - BAD_CVV2', '20', 'SR','BAD_CVV2');

-- ATM deposit transaction fee codes
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'ATM_DEPOSIT - APPROVED', '21', '00','APPROVED');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'ATM_DEPOSIT - INSUFFICIENT_FUNDS', '21', '51','INSUFFICIENT_FUNDS');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'ATM_DEPOSIT - EXCEEDS_WITHDRAW_FREQUENCY_LIMIT', '21', '65','EXCEEDS_WITHDRAW_FREQUENCY_LIMIT');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'ATM_DEPOSIT - EXCEEDS_WITHDRAW_AMOUNT_LIMIT', '21', '61','EXCEEDS_WITHDRAW_AMOUNT_LIMIT');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'ATM_DEPOSIT - CVV_FAILED', '21', '89','CVV_FAILED');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'ATM_DEPOSIT - EXPIRED_CARD', '21', '54','EXPIRED_CARD');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'ATM_DEPOSIT - INVALID_AMOUNT', '21', '13','INVALID_AMOUNT');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'ATM_DEPOSIT - INCORRECT_PIN', '21', '55','INCORRECT_PIN');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'ATM_DEPOSIT - BAD_CVV2', '21', 'SR','BAD_CVV2');

-- Balance Inquiry transaction fee codes
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'BALANCE_INQUIRY - APPROVED', '31', '00','APPROVED');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'BALANCE_INQUIRY - INSUFFICIENT_FUNDS', '31', '51','INSUFFICIENT_FUNDS');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'BALANCE_INQUIRY - EXCEEDS_WITHDRAW_FREQUENCY_LIMIT', '31', '65','EXCEEDS_WITHDRAW_FREQUENCY_LIMIT');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'BALANCE_INQUIRY - EXCEEDS_WITHDRAW_AMOUNT_LIMIT', '31', '61','EXCEEDS_WITHDRAW_AMOUNT_LIMIT');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'BALANCE_INQUIRY - CVV_FAILED', '31', '89','CVV_FAILED');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'BALANCE_INQUIRY - EXPIRED_CARD', '31', '54','EXPIRED_CARD');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'BALANCE_INQUIRY - INVALID_AMOUNT', '31', '13','INVALID_AMOUNT');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'BALANCE_INQUIRY - INCORRECT_PIN', '31', '55','INCORRECT_PIN');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'BALANCE_INQUIRY - BAD_CVV2', '31', 'SR','BAD_CVV2');

-- POS pinless ecom purchase transaction fee codes
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_ECOM_PURCHASE - APPROVED', '50', '00','APPROVED');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_ECOM_PURCHASE - INSUFFICIENT_FUNDS', '50', '51','INSUFFICIENT_FUNDS');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_ECOM_PURCHASE - EXCEEDS_WITHDRAW_FREQUENCY_LIMIT', '50', '65','EXCEEDS_WITHDRAW_FREQUENCY_LIMIT');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_ECOM_PURCHASE - EXCEEDS_WITHDRAW_AMOUNT_LIMIT', '50', '61','EXCEEDS_WITHDRAW_AMOUNT_LIMIT');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_ECOM_PURCHASE - CVV_FAILED', '50', '89','CVV_FAILED');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_ECOM_PURCHASE - EXPIRED_CARD', '50', '54','EXPIRED_CARD');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_ECOM_PURCHASE - INVALID_AMOUNT', '50', '13','INVALID_AMOUNT');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_ECOM_PURCHASE - INCORRECT_PIN', '50', '55','INCORRECT_PIN');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_ECOM_PURCHASE - BAD_CVV2', '50', 'SR','BAD_CVV2');

-- POS pinless ecom credit transaction fee codes
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_ECOM_CREDIT - APPROVED', '55', '00','APPROVED');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_ECOM_CREDIT - INSUFFICIENT_FUNDS', '55', '51','INSUFFICIENT_FUNDS');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_ECOM_CREDIT - EXCEEDS_WITHDRAW_FREQUENCY_LIMIT', '55', '65','EXCEEDS_WITHDRAW_FREQUENCY_LIMIT');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_ECOM_CREDIT - EXCEEDS_WITHDRAW_AMOUNT_LIMIT', '55', '61','EXCEEDS_WITHDRAW_AMOUNT_LIMIT');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_ECOM_CREDIT - CVV_FAILED', '55', '89','CVV_FAILED');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_ECOM_CREDIT - EXPIRED_CARD', '55', '54','EXPIRED_CARD');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_ECOM_CREDIT - INVALID_AMOUNT', '55', '13','INVALID_AMOUNT');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_ECOM_CREDIT - INCORRECT_PIN', '55', '55','INCORRECT_PIN');
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'POS_ECOM_CREDIT - BAD_CVV2', '55', 'SR','BAD_CVV2');

-- Inactivity fee transaction fee codes
INSERT INTO PG_FEE_CODE VALUES(PG_SEQ_FEE_CODE.NEXTVAL, 'CARD INACTIVITY FEE', NULL, NULL,'CARD_INACTIVITY_FEE');

INSERT
INTO "CHATAK_PG_ACQ_DEVC"."PG_APPLICATION_CLIENT"
  (
    ID,
    APP_NAME,
    APP_DESCRIPTION,
    APP_ADMIN_EMAIL,
    APP_CLIENT_NAME,
    APP_CLIENT_EMAIL,
    APP_CLIENT_PHONE,
    APP_CLIENT_ADDRESS,
    APP_CLIENT_CITY,
    APP_CLIENT_COUNTRY,
    APP_CLIENT_ZIP,
    APP_CLIENT_ROLE,
    STATUS,
    ACTIVE_FROM,
    ACTIVE_TILL,
    APP_CLIENT_ID,
    APP_CLIENT_ACCESS,
    APP_AUTH_USER,
    APP_AUTH_PASS,
    CREATED_BY,
    UPDATED_BY,
    CREATED_DATE,
    UPDATED_DATE
  )
  VALUES
  (
    '1',
    'Chatak Pay',
    'Online Checkout',
    'raj.k@girmiti.com',
    'PHP Online Checkout',
    'raj.k@girmiti.com',
    '+919632506005',
    'Bangalore',
    'Bangalore',
    'IND',
    '560037',
    'ROLE_APP',
    '0',
    TO_TIMESTAMP('01-02-15 01:00:00 AM', 'DD-MM-RR HH12:MI:SSXFF AM'),
    TO_TIMESTAMP('01-02-16 11:00:00 PM', 'DD-MM-RR HH12:MI:SSXFF AM'),
    'ABCD1234',
    'ABCDPASS1234',
    'ABCDAUTH1234',
    'ABCDAUTHPASS1234',
    '1',
    '1',
    SYSDATE,
    SYSDATE
  );
  
-- 03/05/15 added insert script for user and role management
-- ----------------------------------------------------
insert into PG_FEATURES values(5,'Reseller','Reseller');
insert into PG_FEATURES values(6,'Role','Role');
insert into PG_SUB_FEATURES values(5,5,'Add Terminal','addTerminal');
insert into PG_SUB_FEATURES values(6,5,'Edit Terminal','editTerminal');
insert into PG_SUB_FEATURES values(7,5,'Search Terminal','searchTerminal');
insert into PG_SUB_FEATURES values(8,5,'Create Merchant','createMerchant');
insert into PG_SUB_FEATURES values(9,5,'Search Merchant','searchMerchant');
insert into PG_SUB_FEATURES values(10,5,'Edit Merchant','editMerchant');
insert into PG_SUB_FEATURES values(11,5,'Delete Merchant','deleteMerchant');
insert into PG_SUB_FEATURES values(12,5,'Create User','createUser');
insert into PG_SUB_FEATURES values(13,5,'Edit User','editUser');
insert into PG_SUB_FEATURES values(14,5,'Delete User','deleteUser');
insert into PG_SUB_FEATURES values(15,5,'Search User','searchUser');
insert into PG_SUB_FEATURES values(16,5,'Search Transaction','transactionReport');
insert into PG_SUB_FEATURES values(17,5,'Search Settlement','Settlement Report');
insert into PG_SUB_FEATURES values(18,6,'Create Role','createRole');
insert into PG_SUB_FEATURES values(19,6,'Edit Role','editRole');
insert into PG_SUB_FEATURES values(20,6,'Delete Role','deleteRole');

INSERT INTO "PG_ACCOUNT" (ID, ENTITY_ID, ENTITY_TYPE, ACCOUNT_DESC, CATEGORY, CURRENT_BALANCE, AVAILABLE_BALANCE, CURRENCY, AUTO_PAYMENT_LIMIT, AUTO_PAYMENT_METHOD, AUTO_TRANSFER_DAY, STATUS, CREATED_DATE, ACCOUNT_NUM, FEE_BALANCE) VALUES ('1', '1', 'Chatak', 'Chatak Revenue Account', 'primary', '0', '0', 'USD', '1111', 'EFT', '3', 'Active', TO_TIMESTAMP('06-05-15 12:31:55.140000000 PM', 'DD-MM-RR HH12:MI:SS.FF AM'), '1000000001', '0');

DELETE FROM PG_STATE;
DELETE FROM PG_COUNTRY;

INSERT INTO PG_COUNTRY(ID, NAME) VALUES (1,'USA');

Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (1,'Alaska','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (2,'Alabama','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (3,'Arizona ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (4,'Arkansas ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (5,'California  ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (6,'Colorado ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (7,'Connecticut ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (8,'Delaware ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (9,'Florida ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (10,'Georgia ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (11,'Hawaii ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (12,'Idaho ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (13,'Illinois ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (14,'Indiana ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (15,'Iowa ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (16,'Kansas ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (17,'Kentucky ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (18,'Louisiana ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (19,'Maine ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (20,'Maryland ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (21,'Massachusetts','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (22,'Michigan ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (23,'Minnesota ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (24,'Mississippi ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (25,'Missouri ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (26,'Montana ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (27,'Nebraska ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (28,'Nevada ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (29,'New Hampshire','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (30,'New Jersey   ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (31,'New Mexico ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (32,'New York ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (33,'North Carolina','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (34,'North Dakota ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (35,'Ohio ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (36,'Oklahoma ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (37,'Oregon       ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (38,'Pennsylvania ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (39,'Rhode Island ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (40,'South Carolina','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (41,'South Dakota ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (42,'Tennessee ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (43,'Texas ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (44,'Utah ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (45,'Vermont ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (46,'Virginia ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (47,'Washington   ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (48,'West Virginia','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (49,'Wisconsin ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (50,'Wyoming ','Active',1);

 
COMMIT;

