   
-- SANDBOX Release on 18/08/2015
--08/08/2015 ADDED FEE CODE FOR PARTNER 
-----------------------------------------------------
--  DDL for Sequence SEQ_PG_PARTNER_FEE_CODE
--------------------------------------------------------
CREATE SEQUENCE SEQ_PG_PARTNER_FEE_CODE MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 10 NOCACHE NOORDER NOCYCLE ;
  --------------------------------------------------------
  --  DDL for Table PG_PARTNER_FEE_CODE
  --------------------------------------------------------
    CREATE TABLE PG_PARTNER_FEE_CODE
    (
      PARTNER_FEE_CODE_ID NUMBER(20,0) NOT NULL ENABLE,
      PARTNER_NAME        VARCHAR2(50),
      PARTNER_ENTITY_ID   VARCHAR2(50 BYTE) NOT NULL ENABLE,
      PARTNER_ENTITY_TYPE VARCHAR2(50 BYTE),
      FEE_PERCENTAGE_ONLY DECIMAL(20,0),
      FLAT_FEE            NUMBER(20,0),
      CREATED_BY          VARCHAR2(20) NOT NULL,
      UPDATED_BY          VARCHAR2(20),
      CREATED_DATE        TIMESTAMP (6) NOT NULL,
      UPDATED_DATE        TIMESTAMP (6),
      ACCOUNT_NUM          NUMBER(20,0)
    );
  ALTER TABLE PG_PARTNER_FEE_CODE ADD CONSTRAINT PG_PARTNER_FEE_CODE_PK PRIMARY KEY (PARTNER_FEE_CODE_ID);
  ALTER TABLE PG_PARTNER_FEE_CODE ADD CONSTRAINT PARTNER_ENTITY_ID_UK UNIQUE (PARTNER_ENTITY_ID);
  ALTER TABLE PG_PARTNER_FEE_CODE ADD CONSTRAINT ACCOUNT_NUM_UK UNIQUE (ACCOUNT_NUM);
  -----------------------------------------------------
--  DDL for Sequence SEQ_PG_PARTNER_FEE_CODE
--------------------------------------------------------

  CREATE SEQUENCE SEQ_PG_ACQUIRER_FEE_CODE MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 10 NOCACHE NOORDER NOCYCLE ;
  --------------------------------------------------------
  --  DDL for Table PG_ACQUIRER_FEE_CODE
  --------------------------------------------------------
    CREATE TABLE PG_ACQUIRER_FEE_CODE
    (
      ACQUIRER_FEE_CODE_ID NUMBER(20,0) NOT NULL ENABLE,
      ACQUIRER_NAME        VARCHAR2(50),
      PARTNER_ID   NUMBER(20,0) NOT NULL ENABLE,
      FEE_PERCENTAGE_ONLY  DECIMAL(20,0),
      FLAT_FEE             NUMBER(20,0),
      UPDATED_BY           VARCHAR2(20),
      UPDATED_DATE         TIMESTAMP (6)
     
    );
  ALTER TABLE PG_ACQUIRER_FEE_CODE ADD CONSTRAINT PG_ACQUIRER_FEE_CODE_PK PRIMARY KEY (ACQUIRER_FEE_CODE_ID);
  ALTER TABLE PG_ACQUIRER_FEE_CODE ADD MERCHANT_CODE VARCHAR2(50);
  ALTER TABLE PG_ACQUIRER_FEE_CODE ADD CONSTRAINT ACQUIRER_NAME_AND_PARTNER_UK UNIQUE (ACQUIRER_NAME,PARTNER_ID,MERCHANT_CODE);
  
    --------------------------------------------------------
  -- 14/08/2015 SEQUENCE FOR  SEQ_PG_TRANSFERS 
  --------------------------------------------------------
    
    CREATE SEQUENCE "SEQ_PG_TRANSFERS"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
       --------------------------------------------------------
  -- 14/08/2015 DDL  for Table PG_TRANSFERS 
  --------------------------------------------------------
CREATE TABLE "PG_TRANSFERS"
    (
      "PG_TRANSFERS_ID"                    NUMBER(10,0) PRIMARY KEY ,
      "AMOUNT"          NUMBER(20,0),
      "MERCHANT_ID"           NUMBER(15,0),
	  "FROM_ACCOUNT"   VARCHAR2(20 BYTE),
	  "TO_ACCOUNT"   VARCHAR2(20 BYTE),
	  "NAME_ON_ACCOUNT"   VARCHAR2(50 BYTE),
	  "CITY"   VARCHAR2(20 BYTE),
	  "STATE"   VARCHAR2(20 BYTE),
	  "ACCOUNT_TYPE"   VARCHAR2(20 BYTE),
	  "BANK_ROUTING_NUMBER"   VARCHAR2(20 BYTE),
	  "TRANSFER_MODE"         VARCHAR2(20 BYTE),
      "CREATED_DATE"          TIMESTAMP (6),
      "UPDATED_DATE"          TIMESTAMP (6),
      "STATUS"                NUMBER(1,0),
      "TXN_DESCRIPTION"       VARCHAR2(500 BYTE)
      
    );
    ALTER TABLE PG_TRANSFERS MODIFY STATUS VARCHAR2(20 BYTE);
        --------------------------------------------------------
  -- 14/08/2015 SEQUENCE FOR  SEQ_PG_LEGAL_ENTITY 
  --------------------------------------------------------
    CREATE SEQUENCE "SEQ_PG_LEGAL_ENTITY" MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 10 NOCACHE NOORDER NOCYCLE ;
            --------------------------------------------------------
  -- 14/08/2015 DDL FOR  PG_LEGAL_ENTITY 
  --------------------------------------------------------
 CREATE TABLE "PG_LEGAL_ENTITY"
  (
    "PG_LEGAL_ENTITY_ID"     NUMBER(10,0) PRIMARY KEY ,
    "LEGAL_ENTITY_NAME"      VARCHAR2(500 BYTE),
    "LEGAL_ENTITY_TYPE"      VARCHAR2(500 BYTE),
    "TAX_ID"                 VARCHAR2(500 BYTE),
    "MERCHANT_ID"            NUMBER(15,0),
    "FIRST_NAME"             VARCHAR2(500 BYTE),
    "LAST_NAME"              VARCHAR2(500 BYTE),
    "DATE_OF_BIRTH"          VARCHAR2(10 BYTE),
    "SSN"                    VARCHAR2(500 BYTE),
    "COUNTRY_OF_RESIDENCE"   VARCHAR2(20 BYTE),
    "COUNTRY_OF_CITIZENSHIP" VARCHAR2(20 BYTE),
    "HOME_PHONE"             VARCHAR2(20 BYTE),
    "MOBILE_PHONE"           VARCHAR2(20 BYTE),
    "ADDRESS1"               VARCHAR2(60 BYTE),
    "ADDRESS2"               VARCHAR2(60 BYTE),
    "CITY"                   VARCHAR2(60 BYTE),
    "STATE"                  VARCHAR2(60 BYTE),
    "COUNTRY"                VARCHAR2(60 BYTE),
    "PIN"                    NUMBER(10,0),
    "PASSPORT_NUMBER"        VARCHAR2(20 BYTE),
    "CREATED_DATE"           TIMESTAMP (6),
    "UPDATED_DATE"           TIMESTAMP (6),
    "ANNUAL_CARD_SALE"       NUMBER(5,0)
  );
  --------------------------------------------------------
  -- 14/08/2015 ALTER SCRIPT FOR  PG_MERCHANT_BANK 
  --------------------------------------------------------
   ALTER TABLE PG_MERCHANT_BANK ADD NAME_ON_ACCOUNT VARCHAR2(50 BYTE);
   ALTER TABLE PG_MERCHANT_BANK ADD ADDRESS1       VARCHAR2(100 BYTE);
   ALTER TABLE PG_MERCHANT_BANK ADD ADDRESS2       VARCHAR2(60 BYTE);
   ALTER TABLE PG_MERCHANT_BANK ADD CITY           VARCHAR2(60 BYTE);
   ALTER TABLE PG_MERCHANT_BANK ADD STATE          VARCHAR2(60 BYTE);
   ALTER TABLE PG_MERCHANT_BANK ADD COUNTRY        VARCHAR2(60 BYTE);
   ALTER TABLE PG_MERCHANT_BANK ADD  PIN            NUMBER(10,0);
   
   ALTER TABLE PG_ACQUIRER_FEE_CODE MODIFY  FEE_PERCENTAGE_ONLY  DECIMAL(20,2);
   --21-08-2015 CHANGES FOR AUTOPAYMET 
   UPDATE PG_ACCOUNT SET AUTO_TRANSFER_DAY=null WHERE 1=1;
   ALTER TABLE PG_ACCOUNT MODIFY  AUTO_TRANSFER_DAY  VARCHAR2(80 BYTE);
   ALTER TABLE PG_ACCOUNT_HISTORY MODIFY  AUTO_TRANSFER_DAY  VARCHAR2(80 BYTE);
   
ALTER table PG_MERCHANT_BANK add MERCHANT_ID NUMBER(15,0);

DELETE FROM PG_STATE;
DELETE FROM PG_COUNTRY;

INSERT INTO PG_COUNTRY(ID, NAME) VALUES (1,'USA');

Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (1,'Alaska','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (2,'Alabama','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (3,'Arizona ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (4,'Arkansas ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (5,'California  ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (6,'Colorado ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (7,'Connecticut ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (8,'Delaware ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (9,'Florida ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (10,'Georgia ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (11,'Hawaii ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (12,'Idaho ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (13,'Illinois ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (14,'Indiana ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (15,'Iowa ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (16,'Kansas ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (17,'Kentucky ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (18,'Louisiana ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (19,'Maine ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (20,'Maryland ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (21,'Massachusetts','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (22,'Michigan ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (23,'Minnesota ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (24,'Mississippi ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (25,'Missouri ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (26,'Montana ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (27,'Nebraska ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (28,'Nevada ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (29,'New Hampshire','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (30,'New Jersey   ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (31,'New Mexico ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (32,'New York ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (33,'North Carolina','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (34,'North Dakota ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (35,'Ohio ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (36,'Oklahoma ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (37,'Oregon       ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (38,'Pennsylvania ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (39,'Rhode Island ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (40,'South Carolina','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (41,'South Dakota ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (42,'Tennessee ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (43,'Texas ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (44,'Utah ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (45,'Vermont ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (46,'Virginia ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (47,'Washington   ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (48,'West Virginia','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (49,'Wisconsin ','Active',1);
Insert into PG_STATE (ID,NAME,STATUS,COUNTRY_ID) values (50,'Wyoming ','Active',1);
 
 
-- Existing user bank and legal entity details update
INSERT
INTO PG_MERCHANT_BANK  (    ID,    BANK_NAME,    BANK_ACC_NUM,    BANK_CODE,    ROUTING_NUMBER,    CURRENCY_CODE,    ACCOUNT_TYPE,    STATUS,    CREATED_DATE,    UPDATED_DATE,    CREATED_BY,    MERCHANT_CODE,    NAME_ON_ACCOUNT,    ADDRESS1,    ADDRESS2,    CITY,    STATE,    COUNTRY,    PIN,    MERCHANT_ID  )  VALUES  (    SEQ_PG_MERCHANT_BANK.NEXTVAL,    'HSBC',    '4327000001',    NULL,    '210000002',    840,    'S',    0,    SYSDATE,    SYSDATE,    5,    NULL,    'Martin',    NULL,    NULL,    NULL,    'Arizona ',    'USA',    120023,    625546158667676  );
INSERT
INTO PG_LEGAL_ENTITY  (    PG_LEGAL_ENTITY_ID,    LEGAL_ENTITY_NAME,    LEGAL_ENTITY_TYPE,    TAX_ID,    MERCHANT_ID,    FIRST_NAME,    LAST_NAME,    DATE_OF_BIRTH,    SSN,    COUNTRY_OF_RESIDENCE,    COUNTRY_OF_CITIZENSHIP,    HOME_PHONE,    MOBILE_PHONE,    ADDRESS1,    ADDRESS2,    CITY,    STATE,    COUNTRY,    PIN,    PASSPORT_NUMBER,    CREATED_DATE,    UPDATED_DATE,    ANNUAL_CARD_SALE  )  VALUES  (    SEQ_PG_LEGAL_ENTITY.NEXTVAL,    'DemoEnitiy',    '1',    '123123123',    625546158667676,    'Demo',    'User',    NULL,    NULL,    NULL,    NULL,    NULL,    '1231231231',    '#12,Test User',    NULL,    'California',    'California  ',    'USA',    123123,    NULL,    SYSDATE,    SYSDATE,    123  );

Update pg_account SET entity_id=1 where id=1;

commit;

-- UPDATED SCRIPT TILL THIS DEPLOYED ON PRODUCTION (28/08/2015) 

-- 
-- 01/09/2015
--------------------------------------------------------
--  DDL for Table PG_PARAMS
--------------------------------------------------------
CREATE TABLE "PG_PARAMS" 
   (
   	"ID"      NUMBER(4,0) PRIMARY KEY,
   	"PARAM_NAME" VARCHAR2(100), 
	"PARAM_VALUE" VARCHAR2(1000),
	"STATUS"      NUMBER(1,0) DEFAULT 1
   );
   
INSERT INTO PG_PARAMS (ID, PARAM_NAME, PARAM_VALUE) values (1, 'LITLE_USER_DEMO', 'Chatak');
INSERT INTO PG_PARAMS (ID, PARAM_NAME, PARAM_VALUE) values (2, 'LITLE_PASS_DEMO', 'chataK$321');
INSERT INTO PG_PARAMS (ID, PARAM_NAME, PARAM_VALUE) values (3, 'LITLE_URL_DEMO', 'https://www.testlitle.com/sandbox/communicator/online');
INSERT INTO PG_PARAMS (ID, PARAM_NAME, PARAM_VALUE) values (4, 'LITLE_MID_DEMO', '93214');

INSERT INTO PG_PARAMS (ID, PARAM_NAME, PARAM_VALUE) values (5, 'LITLE_USER_PRELIVE', 'RAPIDS');
INSERT INTO PG_PARAMS (ID, PARAM_NAME, PARAM_VALUE) values (6, 'LITLE_PASS_PRELIVE', 'certYv4d');
INSERT INTO PG_PARAMS (ID, PARAM_NAME, PARAM_VALUE) values (7, 'LITLE_URL_PRELIVE', 'https://prelive.litle.com/vap/communicator/online');
INSERT INTO PG_PARAMS (ID, PARAM_NAME, PARAM_VALUE) values (8, 'LITLE_MID_PRELIVE', '7103428');

INSERT INTO PG_PARAMS (ID, PARAM_NAME, PARAM_VALUE) values (9, 'LITLE_USER_LIVE', 'RAPIDS');
INSERT INTO PG_PARAMS (ID, PARAM_NAME, PARAM_VALUE) values (10, 'LITLE_PASS_LIVE', 'Yv4dj3x2');
INSERT INTO PG_PARAMS (ID, PARAM_NAME, PARAM_VALUE) values (11, 'LITLE_URL_LIVE', 'https://payments.litle.com/vap/communicator/online');


ALTER TABLE PG_MERCHANT ADD LITLE_MID VARCHAR2(50 BYTE);

ALTER TABLE PG_ONLINE_TXN_LOG ADD APP_MODE VARCHAR2(50 BYTE);

ALTER TABLE PG_TRANSACTION ADD TXN_MODE VARCHAR2(50 BYTE);

ALTER TABLE PG_SWITCH_TRANSACTION ADD TXN_MODE VARCHAR2(50 BYTE);

--20150803 ALTER SCRIPT FOR PG_TRANSACTION  ACQ_CHANNEL 
ALTER TABLE PG_TRANSACTION MODIFY ACQ_CHANNEL VARCHAR2(30) DEFAULT 'web';

-- Need to change this for Production, this should be executed only once.
UPDATE PG_MERCHANT SET LITLE_MID='7103428' WHERE 1=1;

INSERT INTO PG_PARAMS (ID, PARAM_NAME, PARAM_VALUE) values (13, 'MAG_TEK_KEY', '796d6b3057566c304c31444664643674344d7030796b47596b6868657166776b55596255777057676c744b6d624246504641652f64513d3d');

--20150915 Added table for user access logs 

CREATE  TABLE PG_USER_ACTIVITY_LOG
  (
    ACTIVITY_LOG_ID  NUMBER(20,0) NOT NULL,
    USER_ID          VARCHAR2(255) DEFAULT NULL,
    LOGIN_SESSION_ID VARCHAR2(255) DEFAULT NULL,
    AUDIT_SECTION    VARCHAR2(255) DEFAULT NULL,
    AUDIT_EVENT      VARCHAR2(255) DEFAULT NULL,
    AUDIT_SERVICE    VARCHAR2(255) DEFAULT NULL,
    REQUEST_DATA     VARCHAR2(4000) DEFAULT NULL,
    DATA_CHANGE      VARCHAR2(255) DEFAULT NULL,
    STATUS           VARCHAR2(500) DEFAULT NULL,
    DESCRIPTION      VARCHAR2(500) DEFAULT NULL,
    IP_ADDRESS       VARCHAR2(500) DEFAULT NULL,
    ACTIVITY_DATE    TIMESTAMP NOT NULL
  );
ALTER TABLE PG_USER_ACTIVITY_LOG ADD CONSTRAINT PG_USER_ACTIVITY_LOG_PK PRIMARY KEY ( ACTIVITY_LOG_ID);

CREATE SEQUENCE "SEQ_PG_USER_ACTIVITY_LOG" MINVALUE 1 MAXVALUE
  99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE NOORDER NOCYCLE ;
  
  --20150803 ALTER SCRIPT FOR PG_LEGAL_ENTITY  ANNUAL_CARD_SALE ,PG_MERCHANT_BANK NAME_ON_ACCOUNT
  
  ALTER TABLE PG_LEGAL_ENTITY MODIFY ANNUAL_CARD_SALE NUMBER(14,0);
  
  ALTER TABLE PG_MERCHANT_BANK MODIFY NAME_ON_ACCOUNT VARCHAR2(150 BYTE);
  
  --20150921 DDL FOR PG_ACCOUNT_FEE_LOG AND SEQ_PG_ACCOUNT_FEE_LOG TO LOG FEE DETAILS DURING TRANSACTION STAGES
  
  CREATE
  TABLE "PG_ACCOUNT_FEE_LOG"
  (
    "ID"                   NUMBER(10,0) PRIMARY KEY,
    "ENTITY_ID"            VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "ENTITY_TYPE"          VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "ACCOUNT_DESC"         VARCHAR2(100 BYTE),
    "CATEGORY"             VARCHAR2(100 BYTE),
    "CURRENCY"             VARCHAR2(20 BYTE) DEFAULT 'USD',
    "STATUS"               VARCHAR2(20 BYTE),
    "CREATED_DATE"         TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_DATE"         TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    "ACCOUNT_NUM"          NUMBER(20,0),
    "PAYMENT_METHOD"       VARCHAR2(20 BYTE),
    "TRANSACTION_ID"       NUMBER(12,0),
    "PARENT_ENTITY_ID"     VARCHAR2(50 BYTE),
    "MERCHANT_FEE"         NUMBER(20,0) DEFAULT 0,
    "CHATAK_FEE"           NUMBER(20,0) DEFAULT 0,
    "TXN_AMOUNT"           NUMBER(20,0) DEFAULT 0
  );
CREATE SEQUENCE "SEQ_PG_ACCOUNT_FEE_LOG" MINVALUE 1 MAXVALUE 9999999999
  INCREMENT BY 1 START WITH 47 NOCACHE NOORDER NOCYCLE ;
  
  --  20150923 PRODUCTION PROCESSOR VALUES INSERT  
TRUNCATE TABLE PG_SWITCH;

INSERT INTO PG_SWITCH (ID,SWITCH_NAME,SWITCH_TYPE,SWITCH_IP,SWITCH_PORT,STATUS,PRIORITY,CREATED_BY,UPDATED_BY) VALUES (1,'LITLE','SOCKET','192.168.1.215','22403',0,1,1,1);


 --  20150923 PRODUCTION PG_MERCHANT APPLICATION MODE UPDATE

UPDATE PG_MERCHANT SET APPLICATION_MODE='LIVE' WHERE APPLICATION_MODE='live';