pipeline {
    agent any
        parameters {
            string(
                name:'URL',
                defaultValue:"default",
                description: "enter URL")
            string(
                name:'groupid',
                defaultValue:'default',
                description:'enter groupid')
            string(
                name:'artifactid1',
                defaultValue:'default',
                description:'enter artifactid1')
            string(
                name:'artifactid2',
                defaultValue:'default',
                description:'enter artifactid2')
            string(
                name:'image',
                defaultValue:'default',
                description:'enter image name')
        }
        stages {
            stage('SCM') {
                steps {
                    script {
                        sh 'rm -rf chatakpg'
                        sh 'git clone -b develop http://prithvi.prasad:girmiti01@192.168.0.116:7990/scm/chat-clp/chatakpg.git'
                    }
                }
            }
            stage('Artifact-Download') {
                steps {
                    script {
                        sh '''
                            cd chatakpg/devops/QA
                            sh file.sh
                        '''
                    }
                }
            }
            stage('Build-APP-Image') {
                steps {
                    script {
                        sh '''
                            cd chatakpg/devops/QA
                            docker build -t $image:${BUILD_NUMBER} .
                        '''
                    }
                }
            }
        }
}
