- hosts: all
  vars:
    provider:
      registry: "{{ registry }}"
      build_number: "{{build_number}}"
  become_user: root
  become: true
  tasks:
    - name: Make sure that we can connect to the machine
      ping:

    - name: stop previous version docker
      shell: docker stop paygate
    
    - name: remove stopped container
      shell: docker rm -f paygate

    - name: docker login
      shell: docker login -u admin -p admin123 192.168.0.91:8082

    - name: pull docker image from docker repo
      shell: docker pull {{registry}}/paygate:{{build_number}}

    - name: create docker image
      shell: docker run -d --name paygate -p 8062:8062 {{registry}}/paygate:{{build_number}}
    - name: mounting logs
      shell: docker run -it -v /home/dockerization/acquirer/gateway/gateway-logs:/usr/local/tomcat/logs /bin/bash
